<!DOCTYPE html>
<html>

<head>
  <title><?php echo $br['title']; ?></title>
  <meta http-equiv="Content-type" content="text/html; charset=UTF-8">
  <meta name="title" content="<?php echo $br['title']; ?>">
  <meta name="description" content="<?php echo $br['description']; ?>">
  <meta name="keywords" content="<?php echo $br['keywords']; ?>">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="pinterest-rich-pin" content="false" />
  <?php if ($br['page'] == 'maintenance') { ?>
  <meta name="robots" content="noindex">
  <meta name="googlebot" content="noindex">
  <?php } ?>

  <?php if ($br['page'] == 'welcome') { ?>
  <meta property="og:title" content="<?php echo $br['title']; ?>" />
  <meta property="og:type" content="article" />
  <meta property="og:url" content="<?php echo $br['config']['site_url']; ?>" />
  <meta property="og:image" content="<?php echo $br['config']['theme_url']; ?>/imgs/og.jpg" />
  <meta property="og:image:secure_url" content="<?php echo $br['config']['theme_url']; ?>/imgs/og.jpg" />
  <meta property="og:description" content="<?php echo $br['description']; ?>" />
  <meta name="twitter:card" content="summary">
  <meta name="twitter:title" content="<?php echo $br['title']; ?>" />
  <meta name="twitter:description" content="<?php echo $br['description']; ?>" />
  <meta name="twitter:image" content="<?php echo $br['config']['theme_url']; ?>/imgs/og.jpg" />
  <?php } ?>

  <?php if (!empty($_SERVER) && !empty($_SERVER['REQUEST_URI'])) {
    $link_text = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
    //$link_text = substr($br['config']['site_url'], 0,strpos($br['config']['site_url'], '://') + 2).parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
  ?>
  <link rel="canonical" href="<?php echo ($link_text) ?>" />
  <?php } ?>
  <link rel="shortcut icon" type="image/png" href="<?php echo $br['config']['theme_url']; ?>/imgs/favicon.ico" />

  <?php if ($br['page'] == 'welcome') { ?>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/glightbox/dist/css/glightbox.min.css" />
  <link rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css" />
  <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
  <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">
  <link rel="stylesheet" href="<?php echo $br['config']['theme_url']; ?>/css/welcome.css">

  <?php } else { ?>
  <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
  <link rel="stylesheet" href="<?php echo $br['config']['theme_url']; ?>/css/style.css">
  <?php } ?>
  <link rel="stylesheet"
    href="<?php echo $br['config']['theme_url']; ?>/css/font-awesome-4.7.0/css/font-awesome.min.css">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.3.0/jquery.form.js"
    integrity="sha512-RTxmGPtGtFBja+6BCvELEfuUdzlPcgf5TZ7qOVRmDfI9fDdX2f1IwBq+ChiELfWt72WY34n0Ti1oo2Q3cWn+kw=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
    <style>
  <?php echo $br['config']['styles_cc']; ?>
  </style>
  <script type="text/javascript">
    <?php echo $br['config']['header_cc']; ?>
      function Br_Ajax_Requests_File() {
        return "<?php echo $br['config']['site_url'] . '/requests.php'; ?>"
      }
      <?php if ($br['config']['smooth_loading'] == 1 && $br['loggedin'] == true) { ?>
        function Br_Ajax_Requests_Filee() {
          return "<?php echo $br['config']['site_url'] . '/ajax_loading.php'; ?>"
        }

        var websiteUrl = "<?php echo $br['config']['site_url']; ?>";
        $(function () {
          var box = $('#contnet');
          var ISAPI = $('#ISAPI').val();
          $(document).on('click', 'a[data-ajax]', function (e) {
            Br_StartBar();
            window.post = 0;
            var url = $(this).attr('data-ajax');
            e.preventDefault();
            if (!ISAPI) {
              if (url == '?index.php?link1=home') {
                $get_value = $('#json-data').val();
                if ($get_value) {
                  json_data = JSON.parse($('#json-data').val());
                  if (json_data.page == 'home') {
                    window.history.pushState({ state: 'new' }, '', websiteUrl);
                    $("html, body").animate({ scrollTop: 0 }, 100);
                    $('.user-details, .pac-container, .lightbox-container').remove();
                    return false;
                  }
                }
              }
              $.post(Br_Ajax_Requests_Filee() + url, { url: url }, function (data) {
                json_data = JSON.parse($(data).filter('#json-data').val());
                if (json_data.welcome_page == 1 || json_data.redirect == 1) {
                  window.location.href = websiteUrl;
                  return false;
                }
                if ($('.message-option-btns').length > 0) {
                  if (json_data.url == 'index.php?index.php?link1=home') {
                    window.location.href = websiteUrl;
                  } else {
                    window.location.href = json_data.url;
                  }
                  return false;
                }
                //document.getElementById('#contnet').innerHTML = data;
                box.html(data);
                if (json_data.is_css_file == 1) {
                  $('.styled-profile').remove();
                  $('footer').append(json_data.css_file);
                  $('.extra-css').html(json_data.css_file_header);
                } else {
                  $('.styled-profile').attr('href', '');
                  $('.extra-css').empty();
                }
                
                if (json_data.page == 'home') {
                  $('.filterby li.filter-by-li').on('click', function (e) {
                    $('.filterby li.filter-by-li').each(function () {
                      $(this).removeClass('avtive');
                      $(this).find('i').addClass('hidden');
                    });
                    $(this).find('i').removeClass('hidden');
                    $(this).addClass('avtive');
                  });
                  window.history.pushState({ state: 'new' }, '', websiteUrl);
                  //window.history.pushState({}, "<?php // echo $br['config']['site_url'] ?>", websiteUrl);
                } else {
                  window.history.pushState({ state: 'new' }, '', json_data.url);
                  //window.history.pushState({}, "<?php // echo $br['config']['site_url'] ?>", json_data.url);
                }
                
                window.onpopstate = function (event) {
                  $(window).unbind('popstate');
                  window.location.href = document.location;
                };

                if (json_data.is_footer == 1 && $('.second-footer').css('display') == 'none') {
                  $('footer .footer-wrapper').show();
                }
                else if (json_data.is_footer == 1 && $('.second-footer').css('display') != 'none') {

                } else {
                  if ($(window).width() < 720) {
                    $('footer .footer-wrapper').show();
                  } else {
                    $('footer .footer-wrapper, .second-footer').hide();
                  }
                }
                document.title = decodeHtml(json_data.title);
                document_title = decodeHtml(json_data.title);
                $("html, body").animate({ scrollTop: 0 }, 150);
                Br_FinishBar();
                $('#hidden-content').empty();
                
              });
              $('.user-details, .pac-container, .lightbox-container').remove();
            }
          });
        });
      <?php } ?>
  </script>

  <?php echo Br_LoadPage('style'); ?>
  
  <?php if (isset($_COOKIE['mode']) && $_COOKIE['mode'] == 'night') { ?>
  <link rel="stylesheet" href="<?php echo $br['config']['theme_url']; ?>/css/dark.css" id="night-mode-css">
  <?php } ?>
</head>

<body>
  <div id="focus-overlay"></div>
  <input type="hidden" class="main_session" value="<?php echo Br_CreateMainSession(); ?>">

  <!-- ---Header div -->
  <?php if (in_array($br['page'], $br['loggedin_pages'])) { ?>
  <header class="header-container">
    <?php echo Br_LoadPage('header/loggedin-header'); ?>
  </header>
  <?php } else { ?>
  <header class="header-container">
    <?php echo Br_LoadPage('header/content'); ?>
  </header>
  <?php } ?>
  <!-- ---Header div END  -->

  <!-- ---Main Content div -->
  <div id="contnet"><?php echo $br['content']; ?></div>
  <!-- ---Main Content div END  -->

  <!-- ---Footer div -->
  <div class="second-footer">
    <?php
    if ($br['page'] == 'welcome') {
      echo Br_LoadPage('footer/welcome');
    } else {
      echo Br_LoadPage('footer/content');
    }
    ?>
  </div>
  <!-- ---Footer div END  -->

  <!-- JS FILES -->
  <?php if ($br['loggedin'] == false) { ?>
  <script type="text/javascript" src="<?php echo $br['config']['theme_url']; ?>/js/welcome.js"></script>
  <?php } ?>
  <script type="text/javascript" src="<?php echo $br['config']['theme_url']; ?>/js/script.js"></script>
  <script>
  <?php echo $br['config']['footer_cc']; ?>
      $(window).on("popstate", function (e) {
        location.reload();
      });
  </script>
  <!-- End 'JS FILES' -->

  <div class="modal fade sun_modal" id="apply-job-modal" role="dialog">
  </div>
</body>

</html>