<section id="forgot-pass-form">
	<div class="row m-0">
		<div class="col-lg-4 offset-lg-2 main-login-box">
			<div class="text-center pb-5 login-top-text">
				<h1 class="login-title text-dark">Forgot your password?</h1>
				<p class="p-1 m-0 font-ubuntu text-black-50">Don't worry, We will help you fine</p>

				<span class="font-ubuntu text-black-50">Create a new <a
						href="<?php echo Br_SeoLink('index.php?link1=register'); ?>">account</a></span>

			</div>
			<?php
            $allow_switch = false;
            if ($br['config']['sms_provider'] == 'twilio') {
	            if ($br['config']['sms_twilio_username'] !== "" and $br['config']['sms_twilio_password'] !== "") {
		            if ($br['config']['emailValidation'] == 1) {
			            if ($br['config']['sms_or_email'] == "sms") {
				            $allow_switch = true;
			            }
		            }
	            }
            } else if ($br['config']['sms_provider'] == 'bulksms') {
	            if ($br['config']['sms_username'] !== "" and $br['config']['sms_password'] !== "") {
		            if ($br['config']['emailValidation'] == 1) {
			            if ($br['config']['sms_or_email'] == "sms") {
				            $allow_switch = true;
			            }
		            }
	            }
            } else if ($br['config']['sms_provider'] == 'infobip') {
	            if ($br['config']['infobip_api_key'] !== "" and $br['config']['infobip_base_url'] !== "") {
		            if ($br['config']['emailValidation'] == 1) {
			            if ($br['config']['sms_or_email'] == "sms") {
				            $allow_switch = true;
			            }
		            }
	            }
            }
            ?>
			<?php if ($allow_switch) { ?>
			<div class="d-flex justify-content-center">
				<form class="x_chooser">
					<p class="title">Recover Password By</p>
					<div class="submit-btn text-center my-5">
						<button type="button" class="btn btn-warning rounded-pill text-dark px-5 sub-btn"
							id="recover_password_by_email">Email</button>&nbsp;&nbsp;
						<button type="button" class="btn btn-dark rounded-pill px-5 sub-btn"
							id="recover_password_by_sms">Phone</button>
					</div>

				</form>
			</div>
			<?php } ?>

			<div class="d-flex justify-content-center">
				<form id="forgot-form" method="post" class="recover_password_by_email" id="log-form" <?php if ($allow_switch) {
	                echo 'style="display: none;"';
                } ?>>
					<div class="hideMsg"><h2 ><span></span></h2></div>
					<div class="alert alert-danger errors" role="alert" style="display: none;"></div>
					<div class="alert alert-success success" role="alert" style="display: none;"></div>
					<p class="title">Forget pass by email</p>
					<div class="form-row my-4">
						<div class="col input-field">
							<input type="email" required name="recoveremail" id="recoveremail" class="form-control"
								placeholder="Email*">
						</div>
					</div>


					<div class="submit-btn text-center my-5">
						<button type="submit"
							class="btn btn-warning rounded-pill text-dark px-5 sub-btn add_br_loader">Send
							Email</button>

					</div>
					<div class="signup__">
						<p>Already have an account?<a 
								href="<?php echo Br_SeoLink('index.php?link1=login'); ?>">Login</a></p>
					</div>

				</form>
			</div>

			<div class="d-flex justify-content-center">
				<form id="forgot-form-sms" class="recover_password_by_sms" method="post" style="display: none;">
					<div class="hideMsg"><h2 ><span></span></h2></div>
					<div class="alert alert-danger errors" role="alert" style="display: none;"></div>
					<div class="alert alert-success success" role="alert" style="display: none;"></div>
					<p class="title">Forgot pass by sms</p>
					<div class="form-row my-4">
						<div class="col input-field">
							<input type="text" required name="recoverphone" id="recoverphone" class="form-control"
								placeholder="Phone*">
						</div>
					</div>

					<div class="submit-btn text-center my-5">
						<button type="submit"
							class="btn btn-mat btn-warning rounded-pill text-dark px-5 sub-btn add_br_loader">Send SMS</button>
					</div>
					<div class="signup__">
						<p>Already have an account?<a class="dec"
							href="<?php echo Br_SeoLink('index.php?link1=login'); ?>">Login</a></p>
					</div>

				</form>
			</div>
		</div>
	</div>
</section>

<script>
	$('#forgot-pass-form').css("background", "url('<?php echo $br['config']['theme_url'] . '/imgs/welcome1.png'; ?>') no-repeat");
	$('#forgot-pass-form').css("background-size", "cover");
	var working = false;
	var $this = $('#forgot-form');
	var $this_sms = $('#forgot-form-sms');
	var $state = $this.find('.errors');
	var $state_s = $this.find('.success');
	var $state_sms = $this_sms.find('.errors');
	var $state_sms_s = $this_sms.find('.success');
	$(function () {
		$('#recover_password_by_email').click(function () {
			$('.x_chooser').hide();
			$('.recover_password_by_email').show();
		});
		$('#recover_password_by_sms').click(function () {
			$('.x_chooser').hide();
			$('.recover_password_by_sms').show();
		});

		Br_SetTimer();
		$this.ajaxForm({
			url: Br_Ajax_Requests_File() + '?f=recover',
			beforeSend: function () {
				working = true;
				$this.find('button').attr("disabled", true);
				$this.find('.add_br_loader').addClass('btn-loading');
			},
			success: function (data) {
				if (data.status == 200) {
					// $state.addClass('success');
					$state_s.show();
					$state_s.html('Email sent successfully');
					$this.find('.add_br_loader').removeClass('btn-loading');
				} else {
					$this.find('button').attr("disabled", false);
					$this.find('.add_br_loader').removeClass('btn-loading');
					$state.html(data.errors);
				}
				working = false;
			}
		});

		$this_sms.ajaxForm({
			url: Br_Ajax_Requests_File() + '?f=recoversms',
			beforeSend: function () {
				working = true;
				$this_sms.find('button').attr("disabled", true);
				$this_sms.find('.add_br_loader').addClass('btn-loading');
			},
			success: function (data) {
				if (data.status == 200) {
					// $state_sms.addClass('success');
					$state_sms_s.show();
					$state_sms_s.html('SMS sent successfully');
					$this_sms.find('.add_br_loader').removeClass('btn-loading');
					setTimeout(function () {
						window.location.href = data.location;
					}, 1000);
				} else {
					$this_sms.find('button').attr("disabled", false);
					$this_sms.find('.add_br_loader').removeClass('btn-loading');
					$state_sms.html(data.errors);
				}
				working = false;
			}
		});

	});
</script>