<div class="Br_about_wrapper_parent">
	<div class="Br_about_wrapper"> 
		<div class="hero hero-overlay"> 
			<div class="container">
				<h1 class="text-center"> 
					<?php echo 'About';?> <?php echo $br['config']['siteName'];?> <br> 
					<small class="site_desc text-center"><?php echo $br['description'];?></small> 
				</h1>
			</div> 
		</div> 
		<div class="full-width-picture" style="background-image: url(<?php echo $br['config']['theme_url'];?>/img/about-us.jpg);"></div> 
	</div>
</div>

<div class="page-margin Br_about_page_margin">
   <div class="wow_content">
      <div class="setting-well">
        <?php echo $br['terms']['about'];?>
      </div>
   </div>
</div>