<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@8.4.5/swiper-bundle.min.css">
<div class="sliderrr">
    <section>
        <div class="container">
            <div class="section-title">
                <h2>What Our Clients Say's</h2>
            </div>
            <div class="testimonials-carousel-wrap">
                <div class="listing-carousel-button listing-carousel-button-next"><i class="fa fa-caret-right" style="color: #fff"></i></div>
                <div class="listing-carousel-button listing-carousel-button-prev"><i class="fa fa-caret-left" style="color: #fff"></i></div>

                <div class="testimonials-carousel">
                    <div class="swiper-container mySwiper">
                        <div class="swiper-wrapper swiper-wrapper">
                            <div class="swiper-slide">
                                <div class="testi-item">
                                    <div class="testi-avatar"><img src="<?php echo $br['config']['theme_url'] . '/imgs/user2.jpg'; ?>"></div>
                                    <div class="testimonials-text-before"><i class="fa fa-quote-left"></i></div>
                                    <div class="testimonials-text">
                                        <div class="listing-rating">
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                        </div>
                                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem
                                            Ipsum has been the industry's standard dummy text ever since the 1500s, when an
                                            unknown printer took a galley of type and scrambled it to make a type specimen
                                            book.</p>

                                        <div class="testimonials-avatar">
                                            <h3>John Doe</h3>
                                            <h4>Owner</h4>
                                        </div>
                                    </div>
                                    <div class="testimonials-text-after"><i class="fa fa-quote-right"></i></div>
                                </div>
                            </div>

                            <!--second--->
                            <div class="swiper-slide">
                                <div class="testi-item">
                                    <div class="testi-avatar"><img src="<?php echo $br['config']['theme_url'] . '/imgs/user3.jpg'; ?>"></div>
                                    <div class="testimonials-text-before"><i class="fa fa-quote-left"></i></div>
                                    <div class="testimonials-text">
                                        <div class="listing-rating">
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                        </div>
                                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem
                                            Ipsum has been the industry's standard dummy text ever since the 1500s, when an
                                            unknown printer took a galley of type and scrambled it to make a type specimen
                                            book.</p>

                                        <div class="testimonials-avatar">
                                            <h3>Doe Boe</h3>
                                            <h4>Director</h4>
                                        </div>
                                    </div>
                                    <div class="testimonials-text-after"><i class="fa fa-quote-right"></i></div>
                                </div>
                            </div>
                            <!--third-->

                            <div class="swiper-slide">
                                <div class="testi-item">
                                    <div class="testi-avatar"><img src="<?php echo $br['config']['theme_url'] . '/imgs/user4.jpg'; ?>"></div>
                                    <div class="testimonials-text-before"><i class="fa fa-quote-left"></i></div>
                                    <div class="testimonials-text">
                                        <div class="listing-rating">
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                        </div>
                                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem
                                            Ipsum has been the industry's standard dummy text ever since the 1500s, when an
                                            unknown printer took a galley of type and scrambled it to make a type specimen
                                            book.</p>

                                        <div class="testimonials-avatar">
                                            <h3>Boe Doe</h3>
                                            <h4>Developer</h4>
                                        </div>
                                    </div>
                                    <div class="testimonials-text-after"><i class="fa fa-quote-right"></i></div>
                                </div>
                            </div>

                            <!--fourth-->
                            <div class="swiper-slide">
                                <div class="testi-item">
                                    <div class="testi-avatar"><img src="<?php echo $br['config']['theme_url'] . '/imgs/user1.jpg'; ?>"></div>
                                    <div class="testimonials-text-before"><i class="fa fa-quote-left"></i></div>
                                    <div class="testimonials-text">
                                        <div class="listing-rating">
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                        </div>
                                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem
                                            Ipsum has been the industry's standard dummy text ever since the 1500s, when an
                                            unknown printer took a galley of type and scrambled it to make a type specimen
                                            book.</p>

                                        <div class="testimonials-avatar">
                                            <h3>Doe John</h3>
                                            <h4>Designer</h4>
                                        </div>
                                    </div>
                                    <div class="testimonials-text-after"><i class="fa fa-quote-right"></i></div>
                                </div>
                            </div>
                            <!--testi end-->
                        </div>
                    </div>
                </div>

                <div class="tc-pagination"></div>
            </div>
    </section>

</div>

<style>
    html {
        overflow-x: hidden;
        height: 100%;
    }

    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;

    }

    body {

        margin: 0;
        padding: 0;
        height: 100%;
        font-size: 13px;
        text-align: center;
        font-family: "Roboto";
        background: #fcfcfd;
    }


    section {
        float: left;
        position: relative;
        padding: 30px 0;
        background: #fcfcfd;
        z-index: 1;
        width: 100%;
    }

    .section-title {
        float: left;
        position: relative;
        width: 100%;
        padding-bottom: 40px;
    }

    .section-title h2 {
        float: left;
        width: 100%;
        text-align: center;
        color: rgb(240, 102, 102);
        font-size: 34px;
        font-weight: 800;
        position: relative;
        margin-top: 65px;
    }

    .section-title:after {
        content: '';
        position: absolute;
        top: 70%;
        left: 50%;
        transform: translateX(-50%);
        width: 0%;
        height: auto;
        border-bottom: 3px solid rgb(240, 102, 102);
        transition: all 0.3s linear;
    }

    .section-title:hover:after {
        width: 27%
    }

    .swiper-container {
        width: 100%;
        height: 100%;
    }

    .listing-carousel-button {
        position: absolute;
        top: 50%;
        width: 80px;
        height: 50px;
        line-height: 50px;
        margin-top: -25px;
        z-index: 100;
        cursor: pointer;
        background: rgb(240, 102, 102);
        box-shadow: 0 9px 26px rgba(58, 87, 135, 0.45);
        transition: all 200ms linear;
        outline: none;
    }

    .listing-carousel-button.listing-carousel-button-next {
        right: -30px;
        padding-right: 20px;
        border-radius: 60px 0 0 60px;
    }

    .listing-carousel-button.listing-carousel-button-prev {
        left: -30px;
        padding-left: 20px;
        border-radius: 0 60px 60px 0;
    }

    .listing-carousel-button.listing-carousel-button-next:hover {
        right: -15px;
        background: rgba(6, 27, 65, 0.4);
    }

    .listing-carousel-button.listing-carousel-button-prev:hover {
        left: -15px;
        background: rgba(6, 27, 65, 0.4);
    }

    .testi-item {
        transition: all .3s ease-in-out;
        transform: scale(0.9);
        opacity: 0.9;
    }

    .testimonials-text {
        padding: 75px 50px 75px;
        overflow: hidden;
        background: #f5f6fa;
        border: 1ps solid #f1f1f1;
        border-radius: 10px;
        transition: all .3s ease-in-out;
    }

    .testimonials-text-after {
        font-style: normal;
        font-weight: normal;
        text-decoration: inherit;
        position: absolute;
        color: #ccc;
        opacity: .3;
        font-size: 35px;
        transition: all 400ms linear;
        bottom: 25px;
        right: 30px;
    }

    .testimonials-text-before {
        font-style: normal;
        font-weight: normal;
        text-decoration: inherit;
        position: absolute;
        color: #ccc;
        opacity: .3;
        font-size: 35px;
        transition: all 400ms linear;
        top: 25px;
        left: 30px;
    }

    .testimonials-text .listing-rating {
        float: none;
        display: inline-block;
        margin-bottom: 12px;


    }

    .listing-rating i {
        color: rgb(240, 102, 102);

    }

    .testimonials-avatar h3 {
        font-weight: 600;
        color: #7d93b2;
        font-size: 18px;
    }

    .testimonials-avatar h4 {
        font-weight: 400;
        font-size: 12px;
        padding-top: 6px;
        color: rgb(240, 102, 102);
    }

    .testimonials-carousel .swiper-slide {
        padding: 30px 0;
    }

    .testi-avatar {
        position: absolute;
        left: 50%;
        top: -30px;
        width: 90px;
        height: 90px;
        margin-left: -45px;
        z-index: 20;
    }

    .testi-avatar img {
        width: 90px;
        height: 90px;
        float: left;
        border-radius: 100%;
        border: 6px solid #fff;
        box-shadow: 0 9px 26px rgba(58, 87, 135, 0.1);
    }

    .swiper-slide-active .testimonials-text {
        background: #fff;
        box-shadow: 0 9px 26px rgba(58, 87, 135, 0.1);
    }

    .testimonials-text p {
        color: #878c9f;
        font-size: 14px;
        font-family: 'PT Sans', sans-serif;

        line-height: 24px;
        padding-bottom: 10px;
        font-weight: 500;
    }

    .text-link {
        position: absolute;
        bottom: 0;
        padding: 15px 0;
        border-radius: 10px 10px 0 0;
        background: #f9f9f9;
        border: 1px solid #eee;
        box-shadow: 0 10px 15px rgba(0, 0, 0, 0.03);
        left: 50%;
        width: 200px;
        margin-left: -100px;
    }

    .swiper-slide-active .testi-item {
        opacity: 1;
        transform: scale(1.0);
    }

    .tc-pagination {
        float: left;
        margin-top: 10px;
        width: 100% !important;
    }

    .tc-pagination_wrap {
        position: absolute;
        bottom: -40px;
        left: 0;
        width: 100%;
    }

    .tc-pagination2 {
        float: none;
        display: inline-block;
        padding: 14px 0;
        background: #fff;
        border-radius: 30px;
        min-width: 250px;
        border-bottom: 0;
    }

    .tc-pagination .swiper-pagination-bullet,
    .tc-pagination2.swiper-pagination-bullet {
        opacity: 1;
        background: rgb(240, 102, 102);
        margin: 0 2px;
        width: 10px;
        height: 10px;
        transition: all 300ms ease-in-out;
    }
</style>

<script src="https://cdn.jsdelivr.net/npm/swiper@8.4.5/swiper-bundle.min.js"></script>

   <script>
      var swiper = new Swiper(".mySwiper", {
        slidesPerView: 1,
        spaceBetween: 20,
        loop: true,
        pagination: {
          el: ".swiper-pagination",
          clickable: true,
        },
        navigation: {
          nextEl: ".listing-carousel-button-next",
          prevEl: ".listing-carousel-button-prev",
        },
      });
</script>