
    <!--nav bar ends here -->
    <!--services cards starts here -->
    <div class="service py-5">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-10 col-11 mx-auto">
            <div class="mt-5 mb-5 text-center">
              <h1 class="service_heading" >Our <span >Services</span></h1>
            </div>
            <div class="row ">
              <!-- left side data -->
              <div class="col-md-6 mt-md-2 m-0">
                <span class="badge-info badge rounded-pill px-3 py-1 my-2 font-weight-dark">
                  What We Do
                </span>
                <h2 style="font-weight:bold;">Awesome with Extra Ordinary Flexibility Features</h2>
                <h6 class="font-weight-light subtitle">You can relay on our amazing features list and also our customer services will be great experience for you without doubt and in no-time</h6>
                <!-- one more grid sys for services -->
                <div class="row mt-md-5">
                  <div class="col-md-6 mt-3">
                    <h4 class="font-weight-medium">Web Development</h4>
                    <p class="para">Technologies:  (HTML, CSS, JS, JQuery, Ajax), Php, NodeJS, Express React, VueJS, Angular, NextJS, Larval PHP Framework, CodeIgniter Php Framework, CSS Frameworks(Bootstrap and Tailwind).
                      DBs:  MySQL, MongoDB, FireStore , FireBase Realtime Database.
                      </p>
                  </div>
                  <div class="col-md-6 mt-3">
                    <h4 class="font-weight-medium">App Development</h4>
                    <p class="para" >Android Studio(Java and Kotlin language), Xamarin Framework(Visual Studio) with C# language, Flutter(Dart language), Python, Swift(IOS Apps).</p>
                  </div>
                  <div class="col-md-6 mt-3">
                    <h4 class="font-weight-medium">Graphics Designing</h4>
                    <p class="para">For Graphics:  Adobe Photoshop, Adobe illustrator, Abode XD, Figma, Canva.
                      For Videos and Animation:  Adobe After Effect, Adobe Premiere Pro.
                    </p>
                  </div>
                  <div class="col-md-6 mt-3">
                    <h4 class="font-weight-medium">Content Writing & Typing</h4>
                    <p class="para">All Microsoft Office Apps.</p>
                  </div>
                  <div class="col-lg-12 my-4" >
                    <a class="btn btn-sm btn-info"  href="#"> Check More </a>
                  </div>
                </div>
              </div>
              <!-- right side data -->
              <div class="col-md-6 mt-md-5 m-0">
                <div class="row wrap-service ">
                  <!-- left side images -->
                  <div class="col-md-6">
                    <div class="row">
                      <div class="col-md-12 img-hover mb-4">
                        <img alt="ux" class="rounded img-shadow img-fluid " src="<?php echo $br['config']['theme_url'].'/imgs/undraw_web_development_0l6v.svg' ?>">
                      </div>
                      <div class="col-md-12 img-hover mb-4">
                        <img alt="ux" class="rounded img-shadow img-fluid" src="<?php echo $br['config']['theme_url'].'/imgs/undraw_app_wireframe_re_d467.svg' ?>">
                      </div>
                    </div>
                  </div>
                  <!-- right side images -->
                  <div class="col-md-6 uneven-box">
                    <div class="row">
                      <div class="col-md-12 img-hover mb-4">
                        <img alt="ux" class="rounded img-shadow img-fluid" src="<?php echo $br['config']['theme_url'].'/imgs/undraw_designer_girl_re_h54c.svg'?>">
                      </div>
                      <div class="col-md-12 img-hover mb-4">
                        <img alt="ux" class="rounded img-shadow img-fluid" src="<?php echo $br['config']['theme_url'].'/imgs/undraw_information_tab_re_f0w3.svg'?>">
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
   