<section id="forgot-pass-form">
  <div class="row m-0">
    <div class="col-lg-4 offset-lg-2 main-register-box">
      <div class="text-center pb-5 login-top-text">
        <h2 class="login-title text-dark">Oops, looks like your account is not activated yet</h2>
        <h4 class="icon" style="color: <?php echo $br['config']['btn_background_color']; ?>"><i
            class="fa fa-user-times"></i>
        </h4>
        <p class="p-1 m-0 font-ubuntu text-black-50">Please choose a method below to activate your account.</p>
      </div>

      <div class="d-flex justify-content-center">
        <form action="#" method="post" class="activate-form">
          <div id="activate-alerts"></div>
          <div class="alert alert-danger errors" role="alert" style="display: none;"></div>
          <div class="alert alert-success success" role="alert" style="display: none;"></div>
          <p class="title">Via E-mail</p>
          <div class="form-row my-4">
            <div class="col input-field">
              <input type="email" name="email" id="email" class="form-control" placeholder="Email">
            </div>
          </div>

          <?php if ($br['config']['sms_or_email'] == 'sms') { ?>
          <p>OR</p>
          <hr>
          <p class="title">Via Phone Number</p>
          <div class="col input-field">
            <input type="text" class="form-control" name="phone_number" placeholder="Phone Number" value="">
          </div><br><br>
          <?php } ?>

          <div class="submit-btn text-center my-5">
            <button type="submit" id="activate-submit" class="btn btn-warning text-dark px-5 sub-btn add_br_loader"><i
                class="fa fa-paper-plane-o progress-icon" data-icon="paper-plane-o"></i> Send
              Confirmation Code</button>
          </div>
        </form>

        <?php if ($br['config']['sms_or_email'] == 'sms') { ?>
        <form action="#" method="post" class="activate-code-form">
          <div id="activate-code-alerts"></div>
          <div class="form-row my-4">
            <div class="col input-field">
              <input type="text" class="form-control" name="confirm_code" placeholder="Confirmation code">
            </div>
          </div>
          <input type="hidden" class="form-control" name="user_id" value="<?php echo $br['user']['uid']; ?>"><br><br>
          <div class="form-group" id="re-send" style="display:none">
            <div class="text-center">Didn't get the code?
              <a href="javascript:void(0);" onclick="Br_ResendCodeAc();"><i class="fa fa-repeat"></i> Resend</a>
            </div>
          </div>
          <div id="hideMsg" class="item">
            You should receive the code within <h2><span></span></h2>
          </div>
          <div class="submit-btn text-center my-5">
          <button type="submit" class="btn btn-success" id="activate-code-submit">
            <i class="fa fa-check progress-icon" data-icon="check"></i> Confirm
          </button>
          </div>
        </form>
        <?php } ?>

      </div>
    </div>
  </div>
</section>


<script>
  $(function () {
    $('.activate-form').ajaxForm({
      url: Br_Ajax_Requests_File() + '?f=resned_ac_email',
      beforeSend: function () {
        Br_progressIconLoader($('.activate-form').find('button'));
        $('#activate-submit').attr('disabled', true);
      },
      success: function (data) {
        $('#activate-submit').attr('disabled', false);
        if (data.status == 200) {
          $('#activate-alerts').html('<div class="success-container">' + data.message + '</div>');
          $('.success-container').fadeIn(300);
        } else if (data.status == 600) {
          $('#activate-alerts').html('<div class="success-container">' + data.message + '</div>');
          $('.success-container').fadeIn(300).delay(2000).fadeOut(300, function () {
            $('.activate-form').fadeOut(300, function () {
              $('.activate-code-form').fadeIn(300);
            });
          });
          Br_SetTimer();
        } else {
          var errors = data.errors.join("<br>");
          $('#activate-alerts').html('<div class="error-container">' + errors + '</div>');
          $('.error-container').fadeIn(300);
        }
        Br_progressIconLoader($('.activate-form').find('button'));
      }
    });

    $('.activate-code-form').ajaxForm({
      url: Br_Ajax_Requests_File() + '?f=confirm_user',
      beforeSend: function () {
        Br_progressIconLoader($('.activate-code-form').find('button'));
        $('#activate-code-submit').attr('disabled', true);
      },
      success: function (data) {
        if (data.status == 200) {
          window.location.href = data.location;
        } else {
          $('#activate-code-submit').attr('disabled', false);
          var errors = data.errors.join("<br>");
          $('#activate-code-alerts').html('<div class="error-container">' + errors + '</div>');
          $('.error-container').fadeIn(300);
        }
        Br_progressIconLoader($('.activate-code-form').find('button'));
      }
    });
  });
  function Br_ResendCodeAc() {
    $('#re-send').hide();
    Br_SetTimer();
    $.post(Br_Ajax_Requests_File() + '?f=resned_code_ac', function (data) {
      if (data.status == 200) {
        $('#activate-code-alerts').html('<div class="success-container">' + data.message + '</div>');
        $('.success-container').fadeIn('fast');
      } else {
        $('#activate-code-submit').attr('disabled', false);
        var errors = data.errors.join("<br>");
        $('#activate-code-alerts').html('<div class="error-container">' + errors + '</div>');
        $('.error-container').fadeIn(300);
      }
    });
  }
</script>