<nav class="navbar navbar-light navbar-expand-md sticky-top py-3 globalnav">
    <div class="container">
        <div class="area">
            <ul class="circles">
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
        </div><a class="navbar-brand d-flex align-items-center" href="<?php echo $br['config']['site_url']; ?>"><img class="img-fluid logoshadow" src="<?php echo $br['config']['theme_url'] . '/imgs/logo.png'; ?>" /></a>
        <?php
        if ($br['loggedin'] == true) {
        echo Br_LoadPage('header/loggedin-header');
        } else {
        echo Br_LoadPage('header/main-header');
        }
        ?>
        

    </div>
    <div class="loader"></div>
</nav>