<?php
if ($br['loggedin'] == true) {
   header("Location: " . $br['config']['site_url']);
   exit();
} else {
  if (isset($_GET['link2'])) {
   if ($_GET['link2'] == 'success') {
?>
<div class="text-center">
   <h2><?php echo 'your_account_activated';?></h2>
   <div class="account-activate-icon"><i class="fa fa-check-circle"></i></div>
   <h4><?php echo str_replace('{login}', 'login', 'free_to_login');?></h4>
</div>
<?php
    } else {
      header("Location: " . Br_SeoLink('index.php?link1=welcome'));
      exit();
    }
  } else if (isset($_GET['email'], $_GET['code']) === true) {
      $email = $_GET['email'];
      $code  = $_GET['code'];
      if (Br_EmailExists($email) === false) {
        header("Location: " . Br_SeoLink('index.php?link1=welcome'));
        exit();
      } else if (Br_ActivateUser($email, $code) === false) {   
        header("Location: " . Br_SeoLink('index.php?link1=welcome'));   
        exit();   
      } else {
        $session = Br_CreateLoginSession(Br_UserIdFromEmail($email));
        $_SESSION['user_id'] = $session;
        setcookie(
            "user_id",
            $session,
            time() + (10 * 365 * 24 * 60 * 60)
        );
        header("Location: " . Br_SeoLink('index.php?link1=start-up'));
        exit();
      }
  } else {
    header("Location: " . Br_SeoLink('index.php?link1=welcome'));
    exit();
  }
}
?>