<section id="welcome">
    <div>
        <img src="<?php echo $br['user']['profile_pic']; ?>" alt="Your Picture Here" class="pic">
        <h1 class="welcomTxt">Welcome, <?php echo $br['user']['fname'] . " " . $br['user']['lname'] ?></h1>
        <?php if ($br['config']['afternoon_system'] == 1) { ?>
        <div class="alert alert-dismissible greetalert hidden" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"
                onclick="setCookie('day_status', '1', 3);"><span aria-hidden="true">&times;</span></button>
            <div id="daynightmsg"></div>
        </div>
        <?php } ?>
        <?php
            if (Br_IsThereAnnouncement() === true) {
                $announcement = Br_GetHomeAnnouncements();
            ?>
        <div class="home-announcement">
            <div class="alert alert-success" style="background-color: white;">
                <span class="close announcements-option" data-toggle="tooltip"
                    onclick="Br_ViewAnnouncement(<?php echo $announcement['id']; ?>);" title="<?php echo 'hide'; ?>">
                    <i class="fa fa-remove"></i>
                </span>
                <?php echo $announcement['text']; ?>
            </div>
        </div>
        <!-- .home-announcement -->
        <?php } ?>
    </div>
</section>

<!-- Newsfeed -->

<section id="Newsfeed">
    <h1 class="headTxt">
        <hr> NewsFeed
        <hr>
    </h1>
    <div class="news">
        <div class="row">


            <div class="col-md-5 mb-4">
                <div class="bg-image hover-overlay ripple shadow-2-strong rounded-5" data-mdb-ripple-color="light">
                    <img src="<?php echo $br['config']['theme_url'] . '/imgs/bg1.png' ?>" class="img-fluid" />
                    <a href="#!">
                        <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                    </a>
                </div>
            </div>

            <div class="col-md-7 mb-4">
                <span class="badge bg-danger px-2 py-1 shadow-1-strong mb-3">News of the day</span>
                <h4><strong>
                        Improve security and privacy by updating http cache
                    </strong></h4>
                <p class="text-muted">
                    Leaky resources from spectre vulnerabilities.
                    The 'Spectre vulnerabilitiy.' allows apage to read an OS Process's memory.
                    This means an attacker can gain unauthorized acess to cross-origin data.
                    As a consequence, modern web browsers have restricted usage of some of their features
                    such as SharedArrayBuffer or hifh resolution timer- to page with cross-origin isolation.

                </p>

                <button type="button" class="btn btn-primary">Read more</button>
            </div>
        </div>
    </div>

    <div class="news">
        <div class="row gx-5">

            <div class="col-md-5 mb-4 ">
                <div class="bg-image hover-overlay ripple shadow-2-strong rounded-5" data-mdb-ripple-color="light">
                    <img src="https://c4.wallpaperflare.com/wallpaper/431/451/684/the-most-beautiful-picture-of-nature-wallpaper-preview.jpg"
                        class="img-fluid" />
                    <a href="#!">
                        <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                    </a>
                </div>
            </div>

            <div class="col-md-7 mb- 4">
                <!-- <span class="badge bg-danger px-2 py-1 shadow-1-strong mb-3">News of the day</span> -->
                <h4><strong> WebAssembly feature detection </strong></h4>
                <p class="text-muted">

                    WebAssembly 1.0 was released four years ago,but development didn't stop there.
                    New features are added through the 'Proposal standarization process.' As is generally
                    the case with new features on the web, their implementation order and timelines can
                    differ significantly between different engines.
                    Some new features improve coe size by adding new instructions for common operations, some
                    add powerful performance primitives, and other improve developer experience and integartion
                    with the rest of the web.
                </p>
                <button type="button" class="btn btn-primary">Read more</button>
            </div>
        </div>
    </div>

    <!--Section: News of the day-->
</section>

<!--  Projects  -->
<section id="project">
    <div class="container-fluid">
        <h1 class="headTxt">
            <hr>
            Projects
            <hr>
        </h1>
        <div class="row justify-content-evenly">
            <div class="card col-md-3">
                <img src="<?php echo $br['config']['theme_url'] . '/imgs/mietbrapp.jpg' ?>" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">MiET BR App</h5>
                    <p class="card-text"> MiET BR App is a simple and awesome Educational life management app.
                        It gives you a quick and simple experience. It provides proper guidance about competitive exam
                        and internships.
                        It provides all the bsic needs like Timetable, Notes, Assignments etc. It also helps students to
                        ask doubts from faculties,peers and increase peace of learning.
                    </p>
                    <a href="#" class="btn btn-primary">Know More</a>
                </div>
            </div>

            <div class="card col-md-3">
                <img src="<?php echo $br['config']['theme_url'] . '/imgs/i.png' ?>" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Go Popular </h5>
                    <p class="card-text"> Go Popular is a short video community app craeted locally.This is a platform
                        to forecast talents to the whole world. This funny video community maker app lets you follow
                        your favourite entertainer for good fun and entertainment. The app is used by young people
                        as an outlet to express themselves.
                    </p>
                    <a href="#" class="btn btn-primary">Know More</a>
                </div>
            </div>
            <div class="card col-md-3">
                <img src="<?php echo $br['config']['theme_url'] . '/imgs/letwetalk.jpg' ?>" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Letswetalk</h5>
                    <p class="card-text">Letswetalk is a website basically used for group video chat, voice calls and
                        text-messaging. Be together whenever, with our freeall-in-one communication website, completed
                        with
                        text-messaging , calling and video chats. Easily sync your messages and contacts to your
                        Android phone and connect wuth anyone,anywhere.</p>
                    <a href="#" class="btn btn-primary">Know More</a>
                </div>
            </div>
            <div class="card col-md-3">
                <img src="<?php echo $br['config']['theme_url'] . '/imgs/splash_logo.png' ?>" class="card-img-top"
                    alt="...">
                <div class="card-body">
                    <h5 class="card-title">StudyKeyx</h5>
                    <p class="card-text"> Connect with Studykeyx is an efficient and transparent manner right from
                        undertanding the topics to clearing the exam. We offer you a on-step solution for all your
                        learning needs. With aq simple user interface, design, and exciting features, our app is the
                        go-to solution for the students. </p>
                    <a href="#" class="btn btn-primary">Know More</a>
                </div>
            </div>
            <div class="card col-md-3">
                <img src="<?php echo $br['config']['theme_url'] . '/imgs/letsbtube.jpg' ?>" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Letsbtube</h5>
                    <p class="card-text">Letsbtube is a most popular distribution website or platform on the
                        internet. It was originally created as a platform for anyone to post any video content
                        they desired. It was hoped that usewrs could use the site to upload, share, and view content
                        without any restriction. </p>
                    <a href="#" class="btn btn-primary">Know More</a>
                </div>
            </div>
            <div class="card col-md-3">
                <img src="<?php echo $br['config']['theme_url'] . '/imgs/worldtalk.jpg' ?>" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">World Talk </h5>
                    <p class="card-text"> World Talk is a social networking website. It is a type of social network
                        where people stay in touch with friends oe family members through online profiles and
                        updates, or find new friends through similar intrests. People engaged in social networking
                        may be doing so as a personal or a buisness ebdeavor. </p>
                    <a href="#" class="btn btn-primary">Know More</a>
                </div>
            </div>
        </div>
    </div>
</section>

<!--  Team Members  -->
<section id="team">
    <div class='container'>
        <div class="header">
            <div class="teamTitle">Meet Our New Members</div>

        </div>
        <div class="row">
            <div class="card col-lg-3 mt-100">
                <div class="card-content">
                    <div class="card-body p-0">
                        <div class="profile"> <img
                                src="<?php echo $br['config']['theme_url'] . '/imgs/itsmebrijesh.jpeg' ?>"> </div>
                        <div class="card-title"> Brijesh Chauhan<br /> <small>(CEO & Founder)</small>
                        </div>
                        <div class="card-subtitle">
                            <p> <small class="text-muted"> Email: brijeshchauhan19@gmail.com <br>
                                    phone: +91 7017442328<br>
                                    Address: Vill.Dulhera Chauhan, Modipuram , Meerut
                                </small> </p>
                            <ul class="social">
                                <li class="email"><a href="mailto:brsoftsol@gmail.com"><img src="email.png" alt=""></a>
                                </li>
                                <li class="phone"></i><a href="tel:+91 00000000"><img src="phone.png" alt=""></a>
                                </li>
                                <li class="linkedin"><a href="https://www.linkedin.com/company/brsoftsol/"><img
                                            src="linkedin.jpg" alt=""></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card col-lg-3 mt-100">
                <div class="card-content">
                    <div class="card-body p-0">
                        <div class="profile"> <img src="https://picsum.photos/500/300?random=1"> </div>
                        <div class="card-title"> AtulPratap Singh<br /> <small> (CO-CEO)</small> </div>
                        <div class="card-subtitle">
                            <p> <small class="text-muted"> Email: Pratapsinghatul111@gmail.com
                                    Phone: +91 8192002404
                                    Address: O-149 PallavPuram, Phase-2, Meerut
                                </small> </p>
                            <ul class="social">
                                <li class="email"><a href="mailto:brsoftsol@gmail.com"><img src="email.png" alt=""></a>
                                </li>
                                <li class="phone"></i><a href="tel:+91 00000000"><img src="phone.png" alt=""></a>
                                </li>
                                <li class="linkedin"><a href="https://www.linkedin.com/company/brsoftsol/"><img
                                            src="linkedin.jpg" alt=""></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card col-lg-3 mt-100">
                <div class="card-content">
                    <div class="card-body p-0">
                        <div class="profile"> <img src="https://picsum.photos/500/300?random=2"> </div>
                        <div class="card-title"> Prakhar Rastogi <br /> <small>(COO)</small> </div>
                        <div class="card-subtitle">
                            <p> <small class="text-muted"> Email: Prakharrastogi99@gmail.com<br>
                                    Phone: +91 9690843212<br>
                                    Address: S-13 Modipuram, Meerut
                                </small> </p>
                            <ul class="social">
                                <li class="email"><a href="mailto:brsoftsol@gmail.com"><img src="email.png" alt=""></a>
                                </li>
                                <li class="phone"></i><a href="tel:+91 00000000"><img src="phone.png" alt=""></a>
                                </li>
                                <li class="linkedin"><a href="https://www.linkedin.com/company/brsoftsol/"><img
                                            src="linkedin.jpg" alt=""></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section>
<!-- .........................roadmap................... -->
<section id="roadmap">
    <h1 class="headTxt">
        <hr>
        Roadmap
        <hr>
    </h1>
    <div class="page">

        <div class="timeline">
            <div class="timeline__group">
                <span class="timeline__year time" aria-hidden="true">2021</span>
                <div class="timeline__cards">
                    <div class="timeline__card card1">
                        <header class="card__header">
                            <time class="time" datetime="2008-02-02">
                                <span class="time__day">4</span>
                                <span class="time__month">sept</span>
                            </time>
                        </header>
                        <div class="card__content">
                            <p> "Br SoftSol is an IT Services providing company". And at the very starting it's only a
                                BR team which work together with positive hope.
                            </p>
                        </div>
                    </div>
                    <div class="timeline__card card1">
                        <header class="card__header">
                            <time class="time" datetime="2008-09-01">
                                <span class="time__day"> 10 </span>
                                <span class="time__month">Dec</span>
                            </time>
                            <h3 class="card__title r-title">Br Team as a Br SoftSol
                        </header>
                        <div class="card__content">
                            <p> </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="timeline__group">
                <span class="timeline__year time" aria-hidden="true">2022</span>
                <div class="timeline__cards">
                    <div class="timeline__card card1">
                        <header class="card__header">
                            <time class="time" datetime="2008-07-14">
                                <span class="time__day">27</span>
                                <span class="time__month">Apr</span>
                            </time>
                        </header>
                        <div class="card__content">
                            <p>Br SOftSol held a well-defined Orientation to provide a proper knoeledge about Our
                                company.
                                In this Orientation we discuss about the features, services , benefits to join us and
                                the infrastructure
                                provided by the Br softsol to the members.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="timeline__group">

                <div class="timeline__cards">
                    <div class="timeline__card card1">
                        <header class="card__header">
                            <time class="time" datetime="2008-08-18">
                                <span class="time__day">5</span>
                                <span class="time__month">May</span>
                            </time>
                        </header>
                        <div class="card__content">
                            <p> On 5th of may we are going to Organize an event basically an interview session in which
                                we choose our new members for company.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<style>
#team {
    margin-top: 100px;
    margin-bottom: 70px;
}

.single-team {
    -webkit-box-shadow: 0px 0px 30px 0px rgba(167, 167, 167, 0.16);
    -moz-box-shadow: 0px 0px 30px 0px rgba(167, 167, 167, 0.16);
    box-shadow: 0px 0px 30px 0px rgba(167, 167, 167, 0.16);
    overflow: hidden;
    border-radius: 10px;
    margin-top: 30px;

    transition: all 0.4s ease;
}

.single-team:hover {
    box-shadow: 0 5px 10px rgba(0, 0, 0, 0.25);
    transform: translateY(-15px);
}

.single-team .team-image {
    position: relative;
}

.single-team .team-image img {
    width: 100%;
}

.single-team .team-image .social {
    position: absolute;
    left: 0;
    right: 0;
    bottom: 25px;
    height: 20px;
}

.single-team .team-image .social ul {
    background-color: rgba(255, 255, 255, 0.23);
    display: inline-block;
    border-radius: 50px;
    padding: 0 13px;
    position: relative;
    z-index: 5;
    overflow: hidden;
}

.single-team .team-image .social ul::before {
    position: absolute;
    content: '';
    width: 100%;
    height: 100%;
    z-index: -1;
    top: 0;
    left: 0;
    background: -webkit-linear-gradient(#fe8464 0%, #fe6e9a 100%);
    background: -o-linear-gradient(#fe8464 0%, #fe6e9a 100%);
    background: linear-gradient(#fe8464 0%, #fe6e9a 100%);
    opacity: 0;
    visibility: hidden;
    -webkit-transition: all 0.3s ease-out 0s;
    -moz-transition: all 0.3s ease-out 0s;
    -ms-transition: all 0.3s ease-out 0s;
    -o-transition: all 0.3s ease-out 0s;
    transition: all 0.3s ease-out 0s;
}

.single-team .team-image .social ul li {
    display: inline-block;
}

.single-team .team-image .social ul li a {
    padding: 15px 13px;
    color: #fff;
}

.single-team .team-content {
    padding: 30px;
}

.single-team .team-content .holder-name a {
    font-size: 20px;
    font-weight: 700;
    color: #2E2E2E;
    text-decoration: none;
}

.single-team .team-content .text {
    font-size: 1em;
    margin-top: 5px;
}

.single-team:hover .team-image .social ul::before {
    opacity: 1;
    visibility: visible;
}

.flex-container {
    display: flex;
    flex-direction: row;
    font-size: 30px;
    margin-top: 130px;

}

.flex-item-left {
    padding: 10px 50px;
    flex: 60%;
    background-image: url("aboutimages/Untitled-3.svg");
    background-size: cover;

}

.flex-item-right {
    padding: 10px 50px;
    flex: 50%;
    background-image: url("aboutimages/circle3.png");
    background-repeat: no-repeat;
}

@media (max-width: 800px) {
    .flex-container {
        flex-direction: column;
        margin-top: 80px;
    }

    .flex-item-left {
        padding: 10px 20px;

    }

    .flex-item-right {
        background: none;
    }

    .flex-item-right,
    .flex-item-left {
        flex: 100%;
    }

    #team {
        margin-top: 30px;
    }

}

.world {
    width: 100%;
    height: auto;
}

.flex-container1 {
    display: flex;
    flex-direction: row;
    font-size: 30px;
    margin-top: 130px;

}

.flex-item-left1 {
    padding: 10px 50px;
    flex: 40%;
    background-image: url("aboutimages/circle1.png");
    background-repeat: no-repeat;


}

.flex-item-right1 {
    padding: 10px 50px;
    flex: 60%;
    padding-right: 70px;
}

@media (max-width: 800px) {
    .flex-container1 {
        flex-direction: column;
        margin-top: 30px;

    }

    .flex-item-right1 {
        padding: 10px 30px;

    }

    .flex-item-left1 {
        background: none;
    }

    .flex-item-right1,
    .flex-item-left1 {
        flex: 100%;
    }

    .heading {
        font-weight: bold;

    }
}

.flex-item-left2 {
    padding: 10px 30px;
    flex: 60%;
    text-transform: uppercase;
}

.flex-item-right2 {
    padding: 10px 10px;
    flex: 40%;
    background-image: url("aboutimages/circle2.png");
    background-repeat: no-repeat;
}

@media (max-width: 800px) {
    .flex-container {
        flex-direction: column-reverse;

    }

    .flex-item-left2 {
        padding: 5px 10px;
    }

    .flex-item-right2 {
        background: none;
    }

    .flex-item-right2,
    .flex-item-left2 {
        flex: 100%;
    }


}

.team {
    width: 100%;
    height: auto;
    padding-right: 50px;
}

.ill {
    width: 100%;
    height: auto;
}

.heading {
    font-size: 9vw;
    margin-left: 30px;
}
.paras {
    font-size: 0.8em;
    margin-left: 30px;
}
p {
    margin: 20px 10px;
    opacity: 65%;
    font-family: 'Quicksand', sans-serif;
}




/* --------------------------------TEAM----------------------------- */




#team {
    margin: 50px auto;
    width: 90%;
    background-size: auto;
    background: linear-gradient(100deg, #5292f3 20%, #0366f9 80%);
    text-align: center;
    border-radius: 20px;
    box-shadow: 0 20px 40px rgba(0, 0, 0, .2);


}

#team .row {
    justify-content: center;

}

.teamTitle {
    margin:50px;
    padding-top: 50px;
    font-size: 2.5rem;
    color: #ffff;
}


.mt-100 {
    margin-top: 100px
}

.profile img {
    width: 120px;
    height: 120px;
    border-radius: 50%;
    position: relative;
    bottom: 40px;


}

.profile img:hover {
    transform: scale(1.2);
}



#team .card-body {
    position: relative;
    bottom: 20px;

}


#team ul {
    list-style: none;
    padding: 0;
}

#team a {
    text-decoration: none;
    color: black;
    font-style: italic;
}


.social li {
    display: inline;
    margin: 50px 10px 5px 10px;


}

.social img {
    height: 40px;
    border-radius: 20%;

}


.social img:hover {
    /* height: 50px; */
    transform: scale(1.3);
}




/* ....................roadmap..................... */
#roadmap {
    max-width: 90%;
    margin: 80px auto;
    text-align: center;

}

.timeline {
    width: 60%;
    margin: 40px auto;

}


.text {
    display: var(--textDisplay, inline-flex);
    font-size: var(--textFontSize, 1rem);
}

.page h1 {
    text-align: center;
}



.time {
    display: var(--timeDisplay, inline-flex);
}

/* ...................project........................ */
#project {
    width: 90%;
    margin: 100px auto;
}

#project h1 {
    margin: 50px auto; 
}

.card img {
    margin-top: 8px;

}

.card {
    border-radius: 15px;
    margin-left: 30px;
    margin-right: 30px;
    margin-bottom: 40px;
    box-shadow: 0 10px 20px rgba(0, 0, 0, .2);


}
#containre{
    margin-top: 10%;
}

#welcome {
    text-align: center;
    margin-top: 8%;
}

.pic {
    height: 100px;
    border-radius: 50%;
    display: inline-block;
}

#editprfl{
    margin-top: 8%;
}

.welcomTxt,
.headTxt .para {
    display: inline-block;
    font-size: 2.5rem;
    font-weight: 700;
    margin: 10px;
}

#welcome p {
    font-style: italic;
    font-size: 15px;
    padding-left: 120px;

}


#Newsfeed {

    width: 90%;
    margin: 50px auto;
}

.headTxt {
    margin-bottom: 25px;
    font-weight: bold;
    text-align: center;
    margin: 80px auto 40px auto;



}

#Newsfeed img {
    border-radius: 10px;
    height: 300px;
    width: 400px;
}

.news {
    margin-top: 40px;
}



.time {
    display: var(--timeDisplay, inline-flex);
}

/*
  extensions
  */

.time__month {
    margin-left: var(--timelineMounthMarginLeft, .25em);
}

/*
  skin
  */

.time {
    padding: var(--timePadding, .25rem 1.25rem .25rem);
    background-color: var(--timeBackgroundColor, #f0f0f0);

    font-size: var(--timeFontSize, .75rem);
    font-weight: var(--timeFontWeight, 700);
    text-transform: var(--timeTextTransform, uppercase);
    color: var(--timeColor, currentColor);
}

/*
  card component
  */

/*
  core styles
  */

.card1 {
    padding: var(--timelineCardPadding, 1.5rem 1.5rem 1.25rem);
}

.card__content {
    margin-top: var(--cardContentMarginTop, .5rem);
}

/*
  skin
  */

.card1 {
    border-radius: var(--timelineCardBorderRadius, 2px);
    border-left: var(--timelineCardBorderLeftWidth, 3px) solid var(--timelineCardBorderLeftColor, var(--uiTimelineMainColor));
    box-shadow: var(--timelineCardBoxShadow, 0 1px 3px 0 rgba(0, 0, 0, .12), 0 1px 2px 0 rgba(0, 0, 0, .24));
    background-color: var(--timelineCardBackgroundColor, #fff);
}

/*
  extensions
  */

.card__title {
    --rTitleMarginTop: var(--cardTitleMarginTop, 1rem);
    font-size: var(--cardTitleFontSize, 1.25rem);
}

/*
  =====
  CORE STYLES
  =====
  */

.timeline {
    display: var(--timelineDisplay, grid);
    grid-row-gap: var(--timelineGroupsGap, 2rem);
}

/*
  1. If timeline__year isn't displaed the gap between it and timeline__cards isn't displayed too
  */

.timeline__year {
    margin-bottom: 1.25rem;
    /* 1 */
}

.timeline__cards {
    display: var(--timeloneCardsDisplay, grid);
    grid-row-gap: var(--timeloneCardsGap, 1.5rem);
}


/*
  =====
  SKIN
  =====
  */

.timeline {
    --uiTimelineMainColor: var(--timelineMainColor, #222);
    --uiTimelineSecondaryColor: var(--timelineSecondaryColor, #fff);

    border-left: var(--timelineLineWidth, 3px) solid var(--timelineLineBackgroundColor, var(--uiTimelineMainColor));
    padding-top: 1rem;
    padding-bottom: 1.5rem;
}

.timeline__year {
    --timePadding: var(--timelineYearPadding, .5rem 1.5rem);
    --timeColor: var(--uiTimelineSecondaryColor);
    --timeBackgroundColor: var(--uiTimelineMainColor);
    --timeFontWeight: var(--timelineYearFontWeight, 400);
}

.timeline__card {
    position: relative;
    margin-left: var(--timelineCardLineGap, 1rem);
}

/*
  1. Stoping cut box shadow
  */

.timeline__cards {
    overflow: hidden;
    padding-top: .25rem;
    /* 1 */
    padding-bottom: .25rem;
    /* 1 */
}

.timeline__card::before {
    content: "";
    width: 100%;
    height: var(--timelineCardLineWidth, 2px);
    background-color: var(--timelineCardLineBackgroundColor, var(--uiTimelineMainColor));

    position: absolute;
    top: var(--timelineCardLineTop, 1rem);
    left: -50%;
    z-index: -1;
}

/*
  =====
  SETTINGS
  =====
  */
/**/
.timeline {
    --timelineMainColor: #4557bb;
}



p {
    margin-top: 0;
    margin-bottom: 1rem;
    line-height: 1.5;
}

p:last-child {
    margin-bottom: 0;
}

.page {

    text-align: center;
    padding: 30px;
}


.substack {
    border: 1px solid #EEE;
    background-color: #fff;
    width: 100%;
    max-width: 480px;
    height: 280px;
    margin: 1rem auto;
    ;
}


.linktr {
    display: flex;
    justify-content: flex-end;
    padding: 2rem;
    text-align: center;
}

.linktr__goal {
    background-color: rgb(209, 246, 255);
    color: rgb(8, 49, 112);
    box-shadow: rgb(8 49 112 / 24%) 0px 2px 8px 0px;
    border-radius: 2rem;
    padding: .75rem 1.5rem;
}

.r-link {
    --uirLinkDisplay: var(--rLinkDisplay, inline-flex);
    --uirLinkTextColor: var(--rLinkTextColor);
    --uirLinkTextDecoration: var(--rLinkTextDecoration, none);

    display: var(--uirLinkDisplay) !important;
    color: var(--uirLinkTextColor) !important;
    text-decoration: var(--uirLinkTextDecoration) !important;
}
</style>


<script type="text/javascript">
    function Br_ViewAnnouncement(id) {
        var announcement_container = $('.home-announcement');
        $.get(Br_Ajax_Requests_File() + '?f=update_announcement_views', {
            id: id
        }, function (data) {
            if (data.status == 200) {
                announcement_container.slideUp(200, function () {
                    $(this).remove();
                });
            }
        });
    }

    function setCookie(cname, cvalue, exdays) {
        var d = new Date();
        d.setTime(d.getTime() + (exdays * 60 * 60 * 1000));
        var expires = "expires=" + d;
        document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
    }

    function getCookieValue(a) {
        var b = document.cookie.match('(^|;)\\s*' + a + '\\s*=\\s*([^;]+)');
        return b ? b.pop() : '';
    }

    $(function () {
        var is_day_enabled = getCookieValue('day_status');
        var myDate = new Date();
        var hrs = myDate.getHours();
        var greet;
        var color;
        var quote;
        if (hrs < 12) {
            greet = '<?php echo 'Good Morning'; ?>, <?php echo $br['user']['name'] ?> <img src="<?php echo $br['config']['theme_url']; ?>/imgs/park.png"/>';
            color = '#7FC583';
            quote = '<?php echo $br['config']['goodMorningQuote']; ?>';
        } else if (hrs >= 12 && hrs <= 18) {
            greet = '<?php echo 'Good Afternoon'; ?>, <?php echo $br['user']['name'] ?> <img src="<?php echo $br['config']['theme_url']; ?>/imgs/desert.png"/>';
            color = '#ffc107';
            quote = '<?php echo $br["config"]["goodAfternoonQuote"]; ?>';
        } else if (hrs >= 18 && hrs <= 24) {
            greet = '<?php echo 'Good Evening'; ?>, <?php echo $br['user']['name'] ?> <img src="<?php echo $br['config']['theme_url']; ?>/imgs/sea.png"/>';
            color = '#FF4F70';
            quote = '<?php echo $br["config"]["goodEveningQuote"]; ?>';
        }
        if (is_day_enabled != 1) {
            setTimeout(function () {
                $('.greetalert').css('border-left', '2.5px solid ' + color);
                $('#daynightmsg').html('<div class="small-texts">' + greet + '</div><p>' + quote + '</p>');
                $('.greetalert').removeClass('hidden');
            }, 100);
        }
    });
</script>