<div class="row">
	<div class="col-lg-1"></div>
	<div class="col-lg-10">

		<div class="page-margin br_content">
			<div class="page-margin br_creads_minstp start_up br__minstp step-three-active">
				<div class="line">
					<div class="line_sec"></div>
					<div class="dot one"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
							viewBox="0 0 24 24">
							<path fill="currentColor" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z" />
						</svg></div>
					<div class="dot two"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
							viewBox="0 0 24 24">
							<path fill="currentColor" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z" />
						</svg></div>
					<div class="dot three"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
							viewBox="0 0 24 24">
							<path fill="currentColor" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z" />
						</svg></div>
				</div>
				<div class="steps">
					<div class="step step-one">Basic</div>
					<div class="step step-two">info</div>
					<div class="step step-three">More</div>
				</div>
				<h2>More Info</h2>
				<h4>Little bit more</h4>
			</div>
			<div class="add-photo br_usr_steps">

				<form class="setting-general-form" id="setting-general-form" method="post" novalidate="">
					<div class="col-md-4">
						<label for="validationCustom02" class="form-label">Your Portfolio Link</label>
						<input type="text" class="form-control" name="portfolio" id="validationCustom02" value="<?php echo $br['user']['portfolio']; ?>"
							required="">
						<div class="valid-feedback">
							Looks good!
						</div>
					</div>

					<div class="col-md-4">
						<label for="validationCustom03" class="form-label">Github Profile Link</label>
						<input type="text" name="githubprofile" class="form-control" value="<?php echo $br['user']['githubprofile']; ?>" id="validationCustom03"
							required="">
						<div class="invalid-feedback">
							Please provide a valid link.
						</div>
					</div>
					<div class="col-md-3">
						<label for="validationCustom05" class="form-label">Instagram Profile Username</label>
						<input type="text" name="instagramprofile" value="<?php echo $br['user']['instagramprofile']; ?>" class="form-control" id="validationCustom05"
							required="">
						<div class="invalid-feedback">
							Please provide a valid link.
						</div>
					</div>
					<input type="hidden" name="user_id" value="<?php echo $br['user']['uid']; ?>">
					<input type="hidden" name="hash_id" value="<?php echo Br_CreateSession(); ?>">
				</form>
				<div class="clear"></div>
			</div>
			<div class="continue-button br_usr_steps_cont">
				<small class="skip-step" onclick="Br_SkipStep('startup_follow');">Skip this Step</small>
				<button class="btn btn-warning rounded-pill" onclick="Br_SubmitInfoForm();">Finish</button>
			</div>
		</div>
	</div>
	<div class="col-lg-1"></div>
</div>

<script type="text/javascript">
	function Br_SubmitInfoForm() {
		$("form.setting-general-form").submit();
	}
	function Br_SkipStep(type) {
		window.location.href = '<?php echo Br_SeoLink('index.php?link1=welcome'); ?>';
	}
	$(function () {
		$('form.setting-general-form').ajaxForm({
			url: Br_Ajax_Requests_File() + '?f=update_user_information_startup&s=update_more_setting',
			beforeSend: function () {
				$('button').attr('disabled', true);
				$('button').text("Please wait");
			},
			success: function (data) {
				if (data.status == 200) {
					window.location.href = '<?php echo Br_SeoLink('index.php?link1=welcome'); ?>';
				} else {
					$('button').attr('disabled', true);
					$('button').text("Error Occured");
				}
			}
		});
	});

</script>