<div class="container-fluid">
            <!-- Changelogs -->
            <div class="block-header">
                <h2>CHANGELOGS <small>Developed by BR TEAM <a href="https://brsoftsol.com" target="_blank">BR SoftSol</a></small></h2>
            </div>
  
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                v1.0
                                <small>08 May 2022 </small>
                            </h2>
                        </div>
                        <div class="body">
                            <ul>
                                <li> [Added] ability to select admins. </li>
                                <li> [Added] photos section. </li>
                                <li> [Added] female avatar for female users. </li>
                                <li> [Added] Few more APIs. (payment methods) </li>
                                <li> [Fixed] 20+ reported bugs.</li>
                                <li> [Fixed] bugs in API.</li>
                            </ul>
                        </div>
                    </div>
                </div>
             </div>
            
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>v1.0</h2>
                        </div>
                        <div class="body">
                            Version 1.0 Alpha working.
                        </div>
                    </div>
                </div>
            </div>
        </div>