<!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Loggedin Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<?php echo $br['config']['site_url']; ?>/index.php?link1=welcome">WelcomeHome</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<?php echo $br['config']['site_url']; ?>/index.php?link1=profile-feed">Feed</a>
        </li>
		<li class="nav-item">
          <a class="nav-link" href="<?php echo $br['config']['site_url']; ?>/index.php?link1=team">Team</a>
        </li>
		<li class="nav-item">
          <a class="nav-link" href="<?php echo $br['config']['site_url']; ?>/index.php?link1=contact-us">Contact</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="<?php echo $br['config']['site_url']; ?>/index.php?link1=edit-profile">Profile</a></li>
            <li><a class="dropdown-item" href="<?php echo $br['config']['site_url']; ?>/admincp">Admin Area</a></li>
            <li><a class="dropdown-item" href="<?php echo $br['config']['site_url']; ?>/index.php?link1=logout">Logout</a></li>
          </ul>
        </li>
        
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav> -->

<nav class="navbar fixed-top navbar-expand-lg navbar-dark ">
  <div class="container-fluid">
    <div class="area">
      <ul class="circles">
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
      </ul>
    </div>
    <a class="navbar-brand " href="<?php echo $br['config']['site_url']; ?>/index.php?link1=home"><img class="logo" src="<?php echo $br['config']['theme_url'] . '/imgs/logo.png'; ?>" alt=""></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<?php echo $br['config']['site_url']; ?>/index.php?link1=welcome">WelcomeHome</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<?php echo $br['config']['site_url']; ?>/index.php?link1=profile-feed">Feed</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<?php echo $br['config']['site_url']; ?>/index.php?link1=team">Team</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<?php echo $br['config']['site_url']; ?>/index.php?link1=contact-us">Contact</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img class="userpic" src="<?php echo $br['user']['profile_pic']; ?>" alt="">
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="<?php echo $br['config']['site_url']; ?>/index.php?link1=edit-profile">Profile</a></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="<?php echo $br['config']['site_url']; ?>/admincp">Admin Area</a></li>
            <li><a class="dropdown-item" href="<?php echo Br_SeoLink('index.php?link1=logout'); ?>">Logout</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="barloading"></div>
<style>
  .navbar {
    display: block;
    box-shadow: 1px -1px 12px -5px grey;
    transition: 0.3s ease-in-out;
    background: -webkit-linear-gradient(to top, #f9f9f9, #080808);
    background: linear-gradient(90deg, #161616e8, #080808);
    padding-top: 0;
    padding-bottom: 0;
    border: none;
  }

  .logo {
    height: 40px;
    margin: 0px 20px;
  }

  .userpic {
    width: 40px;
    height: 40px;
  }

  .navbar-toggler .collapse {
    border: none;
    outline: none;
  }

  .navbar-nav {
    margin-left: auto;

  }

  .navbar-toggler {
    width: 10px;
    height: 30px;
    border: none;
    margin-right: 30px;
  }

  .navbar-nav li {
    padding: 7px 10px;
  }


  .btn:hover {
    color: #f2709c;
    background: #fff;
    border: 1px solid #f2709c;
  }

  .navbar .navbar-nav .nav-link {
    color: #fff;
    font-size: 1.1em;
  }

  .navbar .navbar-nav .nav-link:hover {
    color: #808080;
  }


  .area {
    background: #4e54c8;
    background: -webkit-linear-gradient(to left, #8f94fb, #4e54c8);
    z-index: -1;
  }

  .circles {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    overflow: hidden;
  }

  .circles li {
    position: absolute;
    display: block;
    list-style: none;
    width: 20px;
    height: 20px;
    background: rgba(255, 255, 255, 0.2);
    animation: animate 25s linear infinite;
    bottom: -150px;

  }

  .circles li:nth-child(1) {
    left: 25%;
    width: 80px;
    height: 80px;
    animation-delay: 0s;
  }


  .circles li:nth-child(2) {
    left: 10%;
    width: 20px;
    height: 20px;
    animation-delay: 2s;
    animation-duration: 12s;
  }

  .circles li:nth-child(3) {
    left: 70%;
    width: 20px;
    height: 20px;
    animation-delay: 4s;
  }

  .circles li:nth-child(4) {
    left: 40%;
    width: 60px;
    height: 60px;
    animation-delay: 0s;
    animation-duration: 18s;
  }

  .circles li:nth-child(5) {
    left: 65%;
    width: 20px;
    height: 20px;
    animation-delay: 0s;
  }

  .circles li:nth-child(6) {
    left: 75%;
    width: 110px;
    height: 110px;
    animation-delay: 3s;
  }

  .circles li:nth-child(7) {
    left: 35%;
    width: 150px;
    height: 150px;
    animation-delay: 7s;
  }

  .circles li:nth-child(8) {
    left: 50%;
    width: 25px;
    height: 25px;
    animation-delay: 15s;
    animation-duration: 45s;
  }

  .circles li:nth-child(9) {
    left: 20%;
    width: 15px;
    height: 15px;
    animation-delay: 2s;
    animation-duration: 35s;
  }

  .circles li:nth-child(10) {
    left: 85%;
    width: 150px;
    height: 150px;
    animation-delay: 0s;
    animation-duration: 11s;
  }

  @keyframes animate {

    0% {
      transform: translateY(0) rotate(0deg);
      opacity: 1;
      border-radius: 0;
    }

    100% {
      transform: translateY(-1000px) rotate(720deg);
      opacity: 0;
      border-radius: 50%;
    }

  }
</style>