<style>

.hero {
  width: 100%;
  height: 100vh;
  background: url('<?php echo $br['config']['theme_url']; ?>/imgs/hero-bg.png') top center no-repeat;
  background-size: cover;
}

.globalnav{
  z-index: 10000;
  position: fixed;
  top: 0px;
  width: 100%;
}
@media (min-width: 1024px) {
  .hero {
    background-attachment: fixed;
  }
}

.btn-loading:after {
	background-color: <?php echo $br['config']['btn_background_color'];?>;
}

.barloading {
    height: 4px;
    width: 100%;
    top: 0px;
    left: 0px;
    right: 0px;
    width: 100%;
    display: none;
    position: fixed;
    z-index: 5000;
    overflow: hidden;
    background-color: #8dd9ff;
}
.barloading:before {
    background-color: #0000000;
}

</style>