<div class="page-margin">
	<div class="wow_main_float_head contactus">
		<div class="container">
			<h1><?php echo 'Terms of use'; ?></h1>
		</div>
	</div>
	
	<div class="wow_main_blogs_bg"></div>
	
	<div class="wow_content Br_terms_page">
		<div class="setting-well">
			<?php echo $br['terms']['terms_of_use'];?>
		</div>
	</div>
</div>

<script>
$('.wow_main_blogs_bg').css('height', ($('.wow_main_float_head').height()) + 'px');
</script>