<!-- <button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navcol-1"><span class="visually-hidden">Toggle
                navigation</span><span class="navbar-toggler-icon"></span></button>
<div id="navcol-1" class="collapse navbar-collapse">
        <ul class="navbar-nav me-auto">
                <li class="nav-item"><a class="nav-link active" href="<?php echo Br_SeoLink('index.php?link1=welcome');?>">Home</a></li>
             
                <li class="nav-item"><a class="nav-link active" href="<?php echo Br_SeoLink('index.php?link1=company-about');?>">About Us</a></li>

               
                <li class="nav-item"><a class="nav-link"
                                href="<?php echo Br_SeoLink('index.php?link1=contact-us'); ?>">Contact Us</a></li>
        </ul><button id="login_btn" class="btn btn-primary navbtn" type="button"
                data-link="<?php echo Br_SeoLink('index.php?link1=login'); ?>">Login</button>
</div>
<script>
        $('#login_btn').click(function () {
                var text = $(this).attr('data-link');
                window.location = text;
        });
</script> -->