<?php
// $cprt = "Copyright"
$copy = str_replace('{site_name}', $br['config']['siteName'], "Copyright &copy; <strong><span>{site_name}</span></strong> {date}");
$copy2 = str_replace('{date}', date('Y'), $copy);
?>


<!--  Footer Start -->
<footer id="footer">
	<div class="footer-top">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-6 footer-contact">
					<h3>BR SoftSol</h3>
					<p>
						Cubical no.1, Miet Incubation Forum,
						<br> Admin-Block, Miet, Nh-58,
						<br> Meerut, UP, India <br> <br>
						<strong>Phone:</strong> +91 7017442328<br>
						<strong>Email:</strong> info@brsoftsol.com<br>
					</p>
				</div>

				<div class="col-lg-2 col-md-6 footer-links">
					<h4 style="font-size: 1.2rem;">Useful Links</h4>
					<ul>
						<li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
						<li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
						<li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
						<li><i class="bx bx-chevron-right"></i> <a data-ajax="?link1=terms&type=terms"
								href="<?php echo Br_SeoLink('index.php?link1=terms&type=terms'); ?>">Terms of service</a>
						</li>
						<li><i class="bx bx-chevron-right"></i> <a data-ajax="?link1=terms&type=privacy-policy"
								href="<?php echo Br_SeoLink('index.php?link1=terms&type=privacy-policy'); ?>">Privacy
								policy</a></li>
						<?php
                        $pages = Br_GetCustomPages();
                        if (count($pages) > 0) {
	                        foreach ($pages as $key => $page) {
                        ?>
						<li><i class="bx bx-chevron-right"></i><a
								href="<?php echo Br_SeoLink('index.php?link1=site-pages&page_name=' . $page['page_name']); ?>"><?php echo $page['page_title']; ?></a></li>
						<?php }
                        } ?>
					</ul>
				</div>

				<div class="col-lg-3 col-md-6 footer-links">
					<h4 style="font-size: 1.2rem;">Our Services</h4>
					<ul>
						<li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
						<li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
						<li><i class="bx bx-chevron-right"></i> <a href="#">App Development</a></li>
						<li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
						<li><i class="bx bx-chevron-right"></i> <a href="#">Content Writer</a></li>
					</ul>
				</div>

				<div class="col-lg-4 col-md-6 footer-newsletter">
					<h4 style="font-size: 1.5rem;">Join Our Newsletter</h4>
					<p>Grow your business with our newsletters</p>
					<form action="" method="post">
						<input type="email" name="email"><input type="submit" value="Subscribe">
					</form>
				</div>

			</div>
		</div>
	</div>

	<div class="container d-md-flex py-4">

		<div class="me-md-auto text-center text-md-start">
			<div class="copyright">
				<?php echo $copy2; ?>. All Rights Reserved
			</div>
			<div class="credits">
				Designed by <a href="https://brsoftsol.com" target="_blank">BR Team</a>
			</div>
		</div>
		<div class="social-links text-center text-md-right pt-3 pt-md-0">
			<a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
			<a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
			<a href="https://www.instagram.com/brsoftsol" target="_blank" class="instagram"><i
					class="bx bxl-instagram"></i></a>
			<a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
			<a href="https://in.linkedin.com/company/brsoftsol" target="_blank" class="linkedin"><i
					class="bx bxl-linkedin"></i></a>
		</div>
	</div>
</footer>
<!-- End Footer -->
<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
      class="bi bi-arrow-up-short"></i></a>