<div class="main-content">
  <!-- Header -->
  <div class="ccheader pb-8 pt-5 pt-lg-8 d-flex align-items-center"
    style="min-height: 600px; background-image: url(''); background-size: cover; background-position: center top;">
    <!-- Mask -->
    <span class="mask bg-gradient-default opacity-8"></span>
    <!-- Header container -->
    <div class="container-fluid d-flex align-items-center">
      <div class="row">
        <div class="col-lg-7 col-md-10">
          <h3 class="display-2 helloheading">Hello,
            <?php echo $br['user_profile']['fname'] . " " . $br['user_profile']['lname']; ?>
          </h3>
          <p class="mt-0 hellodesc mb-5">This is your profile page. You can see the progress you've made with your work
            and manage your projects or assigned tasks</p>
          <a href="#!" class="btn btn-info">Edit profile</a>
        </div>
      </div>
    </div>
  </div>
  <!-- Page content -->
  <div class="container-fluid contfldlst mt--7">
    <div class="row">
      <div class="col-xl-4 order-xl-2 mb-5 mb-xl-0">
        <div class="card card-profile shadow">
          <div class="row justify-content-center">
            <div class="col-lg-2 order-lg-2">
              <div class="card-profile-image">

                <img src="<?php echo $br['user_profile']['profile_pic']; ?>" class="rounded-circle">

              </div>
            </div>
          </div>
          <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
            <div class="d-flex justify-content-between">
              <a href="#" class="btn btn-sm btn-info mr-4">Connect</a>
              <a href="#" class="btn btn-sm btn-default float-right">Message</a>
            </div>
          </div>
          <div class="card-body cardcc pt-0 pt-md-4">
            <div class="row">
              <div class="col">
                <div class="card-profile-stats d-flex justify-content-center mt-md-5">
                  <div>
                    <span class="heading">
                      <?php echo $br['user_profile']['registered']; ?>
                    </span>
                    <span class="description">Registered Date</span>
                  </div>
                  <div>
                    <span class="heading">
                      <?php echo $br['user_profile']['gender']; ?>
                    </span>
                    <span class="description">Gender</span>
                  </div>
                  <div>
                    <span class="heading">
                      <?php echo $br['user_profile']['lastseen']; ?>
                    </span>
                    <span class="description">Last Seen</span>
                  </div>
                </div>
              </div>
            </div>
            <div class="text-center">
              <h3>
                <?php echo $br['user_profile']['fname'] . " " . $br['user_profile']['lname']; ?><span
                  class="font-weight-light"></span>
              </h3>

              <div class="h5 mt-4">
                <!--Brijesh tujha ya par jo post hn teri uska field krna hoga 
                uska baad database sa fetch krdio-->
                <i class="ni business_briefcase-24 mr-2"></i>Founder and CEO
              </div>
              <div>
                <!--Brijesh ya par tujha department show krna hn-->
                <span>Department: </span><br>
                <i class="ni education_hat mr-2"></i>Board of Director
              </div>
              <hr class="my-4">
              <p>Ryan — the name taken by Melbourne-raised, Brooklyn-based Nick Murphy — writes, performs and records
                all of his own music.</p>
              <a href="#">Show more</a>
            </div>
          </div>
        </div>
      </div>

      <div class="col-xl-8 order-xl-1">
        <div class="card colrcard shadow">
          <div class="card-header bg-white border-0">
            <div class="row align-items-center">
              <div class="col-8">
                <ul id="myTab" class="nav nav-tabs">
                  <li class="nav-item">
                    <a href="#home" class="nav-link active" data-bs-toggle="tab">Basic</a>
                  </li>
                  <li class="nav-item">
                    <a href="#profile" class="nav-link" data-bs-toggle="tab">Personal</a>
                  </li>
                  <li class="nav-item">
                    <a href="#review" class="nav-link" data-bs-toggle="tab">Reviews</a>
                  </li>


                </ul>
              </div>

            </div>
          </div>
          <div class="card-body cardcc">
            <div class="tab-content">
              <div class="tab-pane fade show active" id="home">
                <form class="form" novalidate="">
                  <div class="row">
                    <div class="col">
                      <div class="row">
                        <div class="col">
                          <div class="form-group">
                            <label>First Name</label>
                            <input class="form-control" type="text" name="name"
                              value="<?php echo $br['user_profile']['fname']; ?>">
                          </div>
                        </div>
                        <div class="col">
                          <div class="form-group">
                            <label>Last Name</label>
                            <input class="form-control" type="text" name="username"
                              value="<?php echo $br['user_profile']['lname']; ?>">
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col">
                          <div class="form-group">
                            <label>Email</label>
                            <input class="form-control" type="text" value="<?php echo $br['user_profile']['email']; ?>">
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col mb-3">
                          <div class="form-group">
                            <label>About</label>
                            <textarea class="form-control" rows="5" placeholder="My Bio"
                              value="<?php echo $br['user_profile']['about']; ?>"></textarea>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-12 col-sm-6 mb-3">
                      <div class="mb-2"><b>Change Password</b></div>
                      <div class="row">
                        <div class="col">
                          <div class="form-group">
                            <label>Current Password</label>
                            <input class="form-control" type="password" required />
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col">
                          <div class="form-group">
                            <label>New Password</label>
                            <input class="form-control" type="password" required />
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col">
                          <div class="form-group">
                            <label>Confirm Password</label>
                            <input class="form-control" type="password" required>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="col-12 col-sm-5 offset-sm-1 mb-3">
                      <div class="mb-2"><b>Keeping in Touch</b></div>
                      <div class="row">
                        <div class="col">
                          <label>Email Notifications</label>
                          <div class="custom-controls-stacked px-2">
                            <div class="custom-control custom-checkbox">
                              <input type="checkbox" class="custom-control-input" id="notifications-blog" checked="">
                              <label class="custom-control-label" for="notifications-blog">Blog posts</label>
                            </div>
                            <div class="custom-control custom-checkbox">
                              <input type="checkbox" class="custom-control-input" id="notifications-news" checked="">
                              <label class="custom-control-label" for="notifications-news">Newsletter</label>
                            </div>
                            <div class="custom-control custom-checkbox">
                              <input type="checkbox" class="custom-control-input" id="notifications-offers" checked="">
                              <label class="custom-control-label" for="notifications-offers">Personal Offers</label>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col d-flex justify-content-end">
                      <button class="btn btn-primary" type="submit">Save Changes</button>
                    </div>
                  </div>
                </form>
              </div>
              <div class="tab-pane fade" id="profile">
                <form class="row g-3 needs-validation" novalidate>
                  <div class="col-md-3">
                    <label for="validationCustom04" class="form-label">Gender</label>
                    <select class="form-select" id="validationCustom04" required>
                      <option selected disabled value="">Choose...</option>
                      <option>Male</option>
                      <option>Female</option>
                      <option>Others</option>

                    </select>

                  </div>

                  <div class="col-md-4">
                    <label for="validationCustom02" class="form-label">Address</label>
                    <input type="text" class="form-control" id="validationCustom02"
                      value="<?php echo $br['user_profile']['address'] ?>" required>
                    <div class="valid-feedback">
                      Looks good!
                    </div>
                  </div>

                  <div class="col-md-4">
                    <label for="validationCustom03" class="form-label">City</label>
                    <input type="text" class="form-control" id="validationCustom03" required>
                    <div class="invalid-feedback">
                      Please provide a valid city.
                    </div>
                  </div>
                  <div class="col-md-3">
                    <label for="validationCustom04" class="form-label">State</label>
                    <select class="form-select" id="validationCustom04" required>
                      <option selected disabled value="">Choose...</option>
                      <option>...</option>
                    </select>

                  </div>
                  <div class="col-md-3">
                    <label for="validationCustom05" class="form-label">Pin Code</label>
                    <input type="number" class="form-control" id="validationCustom05" required>
                    <div class="invalid-feedback">
                      Please provide a valid zip.
                    </div>
                  </div>
                  <div class="col-md-3">
                    <label for="validationCustom05" class="form-label">College Name</label>
                    <input type="text" class="form-control" id="validationCustom05" required>
                    <div class="invalid-feedback">
                      Please provide a valid zip.
                    </div>
                  </div>
                  <div class="col-md-3">
                    <label for="validationCustom04" class="form-label">Depeartment</label>
                    <select class="form-select" id="validationCustom04" required>
                      <option selected disabled value="">Choose...</option>
                      <option>Web Development</option>
                      <option>App Development</option>
                      <option>Graphic Designing</option>
                      <option>Content Writing</option>
                    </select>

                  </div>
                  <div class="col-md-3">
                    <label for="validationCustom05" class="form-label">Aadhar No</label>
                    <input type="number" class="form-control" id="validationCustom05" required>

                  </div>
                  <div class="col-md-3">
                    <label for="validationCustom05" class="form-label">Github UserName</label>
                    <input type="text" class="form-control" id="validationCustom05" required>

                  </div>
                  <div class="col-md-3">
                    <label for="validationCustom05" class="form-label">DOB</label>
                    <div class="input-group date" id="datepicker">
                      <input type="date" class="form-control" id="date"
                        value="<?php echo is_object($br['user_profile']['birthday']) ? $br['user_profile']['birthday']->format("dd-mm-YY") : $br['user_profile']['birthday'] ?>" />

                    </div>
                  </div>

                  <div class="col-12 d-flex justify-content-end">
                    <button class="btn btn-primary" type="submit">Save Changes</button>
                  </div>
                </form>
              </div>
              <div class="tab-pane fade" id="review">
                <div class="mx-0 mx-sm-auto">
                  <div class="card">
                    <div class="modal-body">
                      <div class="text-center">
                        <i class="far fa-file-alt fa-4x mb-3 text-primary"></i>
                        <p>
                          <strong>Your opinion matters</strong>
                        </p>
                        <p>
                          Have some ideas how to improve our product?
                          <strong>Give us your feedback.</strong>
                        </p>
                      </div>

                      <hr />

                      <form class="px-4" action="">
                        <p class="text-center"><strong>Your rating:</strong></p>

                        <div class="form-check mb-2">
                          <input class="form-check-input" type="radio" name="rating" id="radio3Example1" />
                          <label class="form-check-label" for="radio3Example1">
                            Very good
                          </label>
                        </div>
                        <div class="form-check mb-2">
                          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example2" />
                          <label class="form-check-label" for="radio3Example2">
                            Good
                          </label>
                        </div>
                        <div class="form-check mb-2">
                          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example3" />
                          <label class="form-check-label" for="radio3Example3">
                            Medicore
                          </label>
                        </div>
                        <div class="form-check mb-2">
                          <input class="form-check-input" type="radio" name="rating" id="radio3Example4" />
                          <label class="form-check-label" for="radio3Example4">
                            Bad
                          </label>
                        </div>
                        <div class="form-check mb-2">
                          <input class="form-check-input" type="radio" name="exampleForm" id="radio3Example5" />
                          <label class="form-check-label" for="radio3Example5">
                            Very bad
                          </label>
                        </div>

                        <p class="text-center"><strong>What could we improve?</strong></p>

                        <!-- Message input -->
                        <div class="form-outline mb-4">
                          <textarea class="form-control" id="form4Example3" rows="4"></textarea>
                          <label class="form-label" for="form4Example3">Your feedback</label>
                        </div>
                      </form>
                    </div>
                    <div class="card-footer text-end">
                      <button type="button" class="btn btn-primary">Submit</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  .mask {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    transition: all .15s ease;
    z-index: -1;
  }

  .bg-gradient-default {
    background: linear-gradient(87deg, #172b4d 0, #1a174d 100%) !important;
    opacity: .8 !important;
  }

  .cardcc {
    padding: 1.5rem;
    flex: 1 1 auto;
  }

  @media (min-width: 768px) {
    .main-content .container-fluid {
      padding-right: 39px !important;
      padding-left: 39px !important;
    }
  }

  .helloheading{
    color: #fff;
    font-size: 3rem;
    font-weight: 700;
  }
  .hellodesc{
    color: #fff;
  }

  .main-content .container-fluid {
    padding-right: 39px !important;
    padding-left: 39px !important;
    align-items: center !important;
    display: flex !important;
    width: 100%;
    margin-right: auto;
    margin-left: auto;
    margin-top: -6rem !important;
  }
  .main-content .contfldlst{
    margin-bottom: 6rem !important;
  }

  .ccheader {
    position: relative;
    padding-top: 8rem !important;
    padding-bottom: 8rem !important;
    align-items: center !important;
    display: flex !important;
  }

  .colrcard {
    background-color: #f7fafc !important;
  }

  .card-profile-image img {
    position: absolute;
    left: 50%;
    max-width: 180px;
    transition: all .15s ease;
    transform: translate(-50%, -30%);
    border-radius: 0.375rem;
  }
</style>