<div class="bgcolr">
                <div class="idheading">
                  <h1>Here is your <span>Id-Card</span></h1>
                </div>
                <div class="card-body " id="mycard">
                    <div class="idcard">
                        <div class="padding">
                            <div class="front">
                                <div class="top">
                                    <img src="<?php echo $br['user']['profile_pic']; ?>"> 
                                </div>
                                <div class="bottom">
                                    <p class="pad"> <?php echo $br['user']['fname'] . " " . $br['user']['lname']; ?></p>
                                    <p class="desi">Web Designer</p>
                                    <div class="barcode">
                                        <img src="<?php echo $br['config']['theme_url'] . '/imgs/qrsample.png'; ?>">
                                        <img src="<?php echo $br['config']['theme_url'] . '/imgs/brlogo.png'; ?>">
                                    </div>
                                    <p class="comp">BR SoftSol</p>
                                </div>
                            </div>
                        </div>
                        <div class="back">
                            <h1 class="Details">Information</h1>
                            <hr>
                            <div class="details-info">
                              <p><b>Email: </b></p>
                                <p class="phone"> <?php echo $br['user']['email']; ?></p>
                                <p><b>Mobile No: </b></p>
                                <p class="phone"><?php echo $br['user']['phone']; ?></p>
                                <p><b>Office Address:</b></p>
                                <p class="phone"><?php echo $br['user']['address']; ?></p>
                                <hr>
                                <p><b>Signature(HEAD)</b></p>
                                <img class="sign" src="<?php echo $br['config']['theme_url'] . '/imgs/brijesh_sign.png'; ?>">
                                    
                                </div>
                                
                            </div>
                            
                        </div>
                        <center><button id="demo" class="btn downloadtable" onclick="downloadtable()">Download</button></center>
                    </div>
              
</div>
   <style>
@import url('https://fonts.googleapis.com/css2?family=Radio+Canada:wght@600&display=swap');


.idheading h1 span{
    color: #0575E6;  
}
.idheading{
    font-family: 'Radio Canada', sans-serif;
   text-align:center;
   margin:30px 0px;
   text-transform: uppercase;
   
   color:#021B79;
   position: relative;
   animation-duration: 2s;
   animation-name: slidein;
   animation-iteration-count: 1;

}

.idheading:after {
    color:#021B79;
  content: '';
  position: absolute;
  top: 100%;
  left: 50%;
  transform: translateX(-50%);
  width: 0%;
  height: auto;
  border-bottom: 3px solid #3e4555;
  transition: all 0.3s linear;
}

.idheading:hover:after {
  width: 24%
}
 #demo{
  
    
    margin-top:25px;
  
    font-size:18px;
    padding:10px 20px;
    border-bottom-left-radius: 13px;
    border-top-right-radius: 13px;
    background: #0575E6; 
    background: -webkit-linear-gradient(to top, #021B79, #0575E6);  
    background: linear-gradient(to top, #021B79, #0575E6);
    color:white;
    font-weight: bold;
    border:none;
    animation-duration: 3.5s;
    animation-name: slidein;
    animation-iteration-count: 1;
    transition: all 0.3s ease;
    letter-spacing: 1px;
}

#demo:hover{
    background:transparent;
    color:#021B79;
   
 
  border:2px solid #021B79;


}



.idcard {
   
    width: 100%;
    display: flex;
   
    justify-content: center;
   
    flex-direction: row;
    animation-duration: 3s;
  animation-name: slidein;
  animation-iteration-count: 1;

}

@keyframes slidein {
  0% {
    transform: translateY(-20px);
    opacity: 0;
  }

  100% {
    transform: translateY(0px);
    opacity: 1;
  }
}
.front{
    box-shadow:2px 2px 10px #2C3E50;
    height: 430px;
    width: 280px;
    position: relative;
    border-radius: 15px;
    transition: all 0.4s ease;
    line-height: 22px;
    
}

.front:hover{
    box-shadow: 0 5px 10px rgba(0, 0, 0, 0.25);
  transform: translateY(-15px);
}
.top{
    height: 30%;
    width: 100%;
    background:#021B79; 

    position: relative;
    z-index: 5;
    border-top-left-radius: 15px;
    border-top-right-radius: 15px;
}

.bottom{
    height: 70%;
    width: 100%;
    position: absolute;
    border-bottom-left-radius: 15px;
    border-bottom-right-radius: 15px;
   background-color:#F0F3F4 ;
}

.top img{
    height: 100px;
    width: 100px;
    background-color: #e6ebe0;
    border-radius: 50px;
    position: absolute;
    top:60px;
    left: 95px;
    border:5px solid white;
}
.bottom p{
    position: relative;
    top: 45px;
    text-align: center;
    text-transform: capitalize;
    font-weight: bold;
    font-size: 20px;
    letter-spacing: 1.5px;
}
.bottom .desi{
    font-size:15px;
    color: grey;
    
    font-family: 'Radio Canada', sans-serif;
}
.bottom .pad{
    font-family: 'Radio Canada', sans-serif;
}

.comp{
    color:#021B79;
    font-size:10px;
    margin-top: 15px;
    opacity: 80%;
}
.barcode img
{
    height: 65px;
    width: 65px;
    text-align: center;
    margin: 5px;
}
.barcode{
    text-align: center;
    position: relative;
    top: 50px;
}

.back
{
    box-shadow:2px 2px 10px black;
    height: 430px;
    width: 290px;
    border-radius: 10px;
    background:#021B79;  /* fallback for old browsers */
    transition: all 0.4s ease;
    border-style:1px solid  grey;   
}
.back:hover{
    box-shadow: 0 5px 10px rgba(0, 0, 0, 0.25);
  transform: translateY(-15px);
}
.qr img{
    height: 80px;
    width: 100%;
    margin: 20px;
    background-color: white;
}

.Details {
    color: white;
    text-align: center;
    padding: 10px;
    font-size: 25px;
}


.details-info{
    color: white;
   
    padding: 0px 1px;
    
    font-size: 16px;
    text-align: center;
    margin-top: 5px;
    line-height: 22px;
}

.sign{
    width:110px;
    height:40px;
    margin-top: 0px;
}
.padding{
    padding-right: 40px;
}
.pad , .desi{
    margin-top:10px;
    
}

hr{
    color:white;
}

@media (max-width:800px)
{
    .idcard{
        
        flex-wrap: wrap;
    }
    .idheading{
        margin:20px 50px;
    }
    .idcard .front{
        margin-top: 30px;
       margin-left:35px;
    }
    .idcard .back{
        margin-top:30px;
    }
  
}




   </style>
<script>
     function downloadtable() {

var node = document.getElementById('mycard');

domtoimage.toPng(node)
    .then(function (dataUrl) {
        var img = new Image();
        img.src = dataUrl;
        downloadURI(dataUrl, "staff-id-card.png")
    })
    .catch(function (error) {
        console.error('oops, something went wrong', error);
    });

}



function downloadURI(uri, name) {
var link = document.createElement("a");
link.download = name;
link.href = uri;
document.body.appendChild(link);
link.click();
document.body.removeChild(link);
delete link;
}

</script>