<section class="team-section py-5" id="team1">
    <h2 id="meet">Meet Our Team</h2>
    <div class="container">
	    <div class="row justify-content-center">
		    <div class="col-12 col-md-6">
			    <div class="card border-0 shadow-lg pt-5 my-5 position-relative">
				    <div class="card-body p-4">
					    <div class="member-profile position-absolute w-100 text-center">
					        <img class="rounded-circle mx-auto d-inline-block shadow-sm" src="<?php echo $br['config']['theme_url'].'/imgs/itsmebrijesh.jpeg'?>" alt="">
				        </div>
					    <div class="card-text pt-1">
						    <h5 class="member-name mb-0 text-center text-primary font-weight-bold">Brijesh Chauhan</h5>
						    <div class="mb-3 text-center">CEO & FOUNDER</div>
						    <div>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Vivamus eget eros vestibulum, accumsan ante viverra, condimentum tellus. Curabitur pellentesque convallis purus non ornare. Donec bibendum sed purus dignissim rutrum. Maecenas bibendum feugiat est, et venenatis nunc.</div>
					    </div>
				    </div>
				    
            </div>
		    </div>
		    
		    <div class="col-12 col-md-6">
			    <div class="card border-0 shadow-lg pt-5 my-5 position-relative">
				    <div class="card-body p-4">
					    <div class="member-profile position-absolute w-100 text-center">
					        <img class="rounded-circle mx-auto d-inline-block shadow-sm" src="<?php echo $br['config']['theme_url'].'/imgs/atul.jpeg'?>" alt="">
				        </div>
					    <div class="card-text pt-1">
						    <h5 class="member-name mb-0 text-center text-primary font-weight-bold">Atul Pratap Singh</h5>
						    <div class="mb-3 text-center">Co-CEO</div>
						    <div>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Vivamus eget eros vestibulum, accumsan ante viverra, condimentum tellus. Curabitur pellentesque convallis purus non ornare. Donec bibendum sed purus dignissim rutrum. Maecenas bibendum feugiat est, et venenatis nunc.</div>
					    </div>
				    </div>
				   
			    </div>
		    </div>
		    
		    <div class="col-12 col-md-6 col-lg-4">
			    <div class="card border-0 shadow-lg pt-5 my-5 position-relative">
				    <div class="card-body p-4">
					    <div class="member-profile position-absolute w-100 text-center">
					        <img class="rounded-circle mx-auto d-inline-block shadow-sm" src="<?php echo $br['config']['theme_url'].'/imgs/prakhar.jpeg'?>" alt="">
				        </div>
					    <div class="card-text pt-1">
						    <h5 class="member-name mb-0 text-center text-primary font-weight-bold">Prakhar Rastogi</h5>
						    <div class="mb-3 text-center">COO</div>
						    <div>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Vivamus eget eros vestibulum, accumsan ante viverra, condimentum tellus. </div>
					    </div>
				    </div>
				    
			    </div>
		    </div>
		    <div class="col-12 col-md-6 col-lg-4">
			    <div class="card border-0 shadow-lg pt-5 my-5 position-relative">
				    <div class="card-body p-4">
					    <div class="member-profile position-absolute w-100 text-center">
					        <img class="rounded-circle mx-auto d-inline-block shadow-sm" src="<?php echo $br['config']['theme_url'].'/imgs/paridhi.jpeg'?>" alt="">
				        </div>
					    <div class="card-text pt-1">
						    <h5 class="member-name mb-0 text-center text-primary font-weight-bold">Pardhi Jain</h5>
						    <div class="mb-3 text-center">CTO</div>
						    <div>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Vivamus eget eros vestibulum, accumsan ante viverra, condimentum tellus.</div>
					    </div>
				    </div>
				    
			    </div>
		    </div>
		    <div class="col-12 col-md-6 col-lg-4">
			    <div class="card border-0 shadow-lg pt-5 my-5 position-relative">
				    <div class="card-body p-4">
					    <div class="member-profile position-absolute w-100 text-center">
					        <img class="rounded-circle mx-auto d-inline-block shadow-sm" src="<?php echo $br['config']['theme_url'].'/imgs/choti.jpeg'?>" alt="">
				        </div>
					    <div class="card-text pt-1">
						    <h5 class="member-name mb-0 text-center text-primary font-weight-bold">Shrestha Johri</h5>
						    <div class="mb-3 text-center">President</div>
						    <div>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Vivamus eget eros vestibulum, accumsan ante viverra, condimentum tellus.</div>
					    </div>
				    </div>
				    
			    </div>
		    </div>
	    </div>
        <div class="col-12 col-md-6 col-lg-4">
			    <div class="card border-0 shadow-lg pt-5 my-5 position-relative">
				    <div class="card-body p-4">
					    <div class="member-profile position-absolute w-100 text-center">
					        <img class="rounded-circle mx-auto d-inline-block shadow-sm" src="<?php echo $br['config']['theme_url'].'/imgs/kansal.jpeg'?>" alt="">
				        </div>
					    <div class="card-text pt-1">
						    <h5 class="member-name mb-0 text-center text-primary font-weight-bold">Shruti Kansal</h5>
						    <div class="mb-3 text-center">Vice-President</div>
						    <div>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Vivamus eget eros vestibulum, accumsan ante viverra, condimentum tellus.</div>
					    </div>
				    </div>
				    
			    </div>
		    </div>
            
            
	    </div>
        
        
	    
    </div>
    
</section>