<!-- ======= Hero Section ======= -->
<section id="hero" class="hero d-flex align-items-center">

    <div class="container">
        <div class="row">
            <div class="col-lg-6 d-flex flex-column justify-content-center">
                <h1 data-aos="fade-up">Create Your
                    Success Business with <br>
                    <span style="color: #4233ff;">BR SOFTSOL</span>
                </h1>
                <h5 data-aos="fade-up" data-aos-delay="400">Solving real-world problems through better design and technology.
                    We don’t just build apps and websites— we create entire experiences. We provide our customers with high-quality,
                    cutting-edge business solutions. Bring your idea to life and get set up for success!</h5>
                <div data-aos="fade-up" data-aos-delay="600">
                    <div class="text-center text-lg-start">
                        <a href="#about" class="btn-get-started scrollto d-inline-flex align-items-center justify-content-center align-self-center">
                            <span>Get Started</span>
                            <i class="bi bi-arrow-right"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 hero-img" data-aos="zoom-out" data-aos-delay="200">
                <img src="<?php echo $br['config']['theme_url']; ?>/imgs/hero-img.png" class="img-fluid" alt="">
            </div>
        </div>
    </div>

</section><!-- End Hero -->


<!-- ====== START ABOUT ======  -->
<section class="about padding" id="about" data-scroll-index="1" style="background: rgb(243, 246, 252); clip-path: polygon(0 0, 100% 0 , 100% 100% , 80% 95% , 0 100%);">
    <div class="container">
        <div class="row">

            <!-- START ABOUT PICTURE -->
            <div class="col-lg-4 mt-lg-2">
                <img src="<?php echo $br['config']['theme_url']; ?>/imgs/about2.png" width="400px" height="400px" alt="about-picture" style="margin-left: -1rem;" />
            </div>
            <!-- END ABOUT PICTURE -->

            <!-- START ABOUT CONTENT -->
            <div class="col-lg-6 mt-md-5 mt-sm-5 about-content" style="margin-left: 10rem;">
                <h2 class="heading-primary mb-5">

                    <img class="about" style="width:200px; height:80px ;justify-content: center;align-items:center; margin:auto; display:flex;" src="<?php echo $br['config']['theme_url']; ?>/imgs/new.png">
                </h2>
                <p class="mb-3">
                    BR Softsol is an IT consulting and solution providing organization for next generation business
                    collaborates
                    throughout the world. With comprehensive intelligence system across diverse industries and
                    domains,
                    we dedicatedly work over the client's project to turn them into some most successful and
                    high-performance organizations.</p>
                <p class="mb-5">
                    Sharpening edges via information and continual learning, all of these aspects contribute to
                    success
                </p>

            </div>
            <!-- END ABOUT CONTENT -->

        </div>
    </div>
</section>
<!-- ====== END ABOUT======  -->



<!-- ======= Features Section ======= -->
<section id="features" class="features">
    <div class="container" data-aos="fade-up">

        <div class="section-title">
            <h2 style="margin-top: 2rem;">why choose us?</h2>
        </div>

        <div class="row">
            <div class="col-lg-6 order-2 order-lg-1 d-flex flex-column align-items-lg-center">
                <div class="icon-box mt-5 mt-lg-0" data-aos="fade-up" data-aos-delay="100">
                    <i class="bx bx-receipt"></i>
                    <p>We create experiences that are attractive, simple to use, and drive results for your company.</p>
                </div>
                <div class="icon-box mt-5" data-aos="fade-up" data-aos-delay="200">
                    <i class="bx bx-cube-alt"></i>
                    <p>We begin each project by gaining a solid understanding of who you are, what you do and why you do it.</p>
                </div>
                <div class="icon-box mt-5" data-aos="fade-up" data-aos-delay="300">
                    <i class="bx bx-images"></i>
                    <p>We determine the scope of the web development project, create a budget and timeline, and once they’re approved, we stick to them. </p>
                </div>

            </div>
            <div class="image col-lg-6 order-1 order-lg-2 " data-aos="zoom-in" data-aos-delay="100">
                <img src="<?php echo $br['config']['theme_url']; ?>/imgs/features.svg" alt="" class="img-fluid">
            </div>
        </div>

    </div>
</section><!-- End Features Section -->


<!-- ======= Services Section ======= -->
<section id="services" class="services">
    <div class="container">

        <div class="section-title">
            <h2>Services</h2>
            <p> <span style="font-size: 1.5rem;">Awesome with Extra Ordinary Flexibility Features</span> <br>
                You can relay on our amazing features list and also our customer services will be great experience for you without doubt and in no-time</p>
        </div>

        <div class="row">

            <div class="col-xl-7">
                <div class="icon-boxes d-flex flex-column justify-content-center">
                    <div class="row">


                        <div class="col-lg-6 d-flex align-items-stretch mt-4 " data-aos="zoom-in" data-aos-delay="200">
                            <div class="icon-box iconbox-orange ">
                                <div class="icon">
                                    <svg width="100" height="100" viewBox="0 0 600 600" xmlns="http://www.w3.org/2000/svg">
                                        <path stroke="none" stroke-width="0" fill="#f5f5f5" d="M300,582.0697525312426C382.5290701553225,586.8405444964366,449.9789794690241,525.3245884688669,502.5850820975895,461.55621195738473C556.606425686781,396.0723002908107,615.8543463187945,314.28637112970534,586.6730223649479,234.56875336149918C558.9533121215079,158.8439757836574,454.9685369536778,164.00468322053177,381.49747125262974,130.76875717737553C312.15926192815925,99.40240125094834,248.97055460311594,18.661163978235184,179.8680185752513,50.54337015887873C110.5421016452524,82.52863877960104,119.82277516462835,180.83849132639028,109.12597500060166,256.43424936330496C100.08760227029461,320.3096726198365,92.17705696193138,384.0621239912766,124.79988738764834,439.7174275375508C164.83382741302287,508.01625554203684,220.96474134820875,577.5009287672846,300,582.0697525312426"></path>
                                    </svg>
                                    <i class='bx bx-code'></i>
                                </div>
                                <h4><a href="">Web Development</a></h4>
                                <p>Technologies: (HTML, CSS, JS, JQuery, Ajax), Php, NodeJS, Express React, VueJS, Angular, NextJS, Larval PHP Framework, CodeIgniter Php Framework, CSS Frameworks(Bootstrap and Tailwind). DBs: MySQL, MongoDB, FireStore , FireBase Realtime Database.</p>
                            </div>
                        </div>

                        <div class="col-lg-6 d-flex align-items-stretch mt-4" data-aos="zoom-in" data-aos-delay="300">
                            <div class="icon-box iconbox-pink">
                                <div class="icon">
                                    <svg width="100" height="100" viewBox="0 0 600 600" xmlns="http://www.w3.org/2000/svg">
                                        <path stroke="none" stroke-width="0" fill="#f5f5f5" d="M300,541.5067337569781C382.14930387511276,545.0595476570109,479.8736841581634,548.3450877840088,526.4010558755058,480.5488172755941C571.5218469581645,414.80211281144784,517.5187510058486,332.0715597781072,496.52539010469104,255.14436215662573C477.37192572678356,184.95920475031193,473.57363656557914,105.61284051026155,413.0603344069578,65.22779650032875C343.27470386102294,18.654635553484475,251.2091493199835,5.337323636656869,175.0934190732945,40.62881213300186C97.87086631185822,76.43348514350839,51.98124368387456,156.15599469081315,36.44837278890362,239.84606092416172C21.716077023791087,319.22268207091537,43.775223500013084,401.1760424656574,96.891909868211,461.97329694683043C147.22146801428983,519.5804099606455,223.5754009179313,538.201503339737,300,541.5067337569781"></path>
                                    </svg>
                                    <i class='bx bxs-devices'></i>
                                </div>
                                <h4><a href="">App Development</a></h4>
                                <p>Android Studio(Java and Kotlin language), Xamarin Framework(Visual Studio) with C# language, Flutter(Dart language), Python, Swift(IOS Apps).</p>
                            </div>
                        </div>

                        <div class="col-lg-6 d-flex align-items-stretch mt-4" data-aos="zoom-in" data-aos-delay="100">
                            <div class="icon-box iconbox-teal">
                                <div class="icon">
                                    <svg width="100" height="100" viewBox="0 0 600 600" xmlns="http://www.w3.org/2000/svg">
                                        <path stroke="none" stroke-width="0" fill="#f5f5f5" d="M300,503.46388370962813C374.79870501325706,506.71871716319447,464.8034551963731,527.1746412648533,510.4981551193396,467.86667711651364C555.9287308511215,408.9015244558933,512.6030010748507,327.5744911775523,490.211057578863,256.5855673507754C471.097692560561,195.9906835881958,447.69079081568157,138.11976852964426,395.19560036434837,102.3242989838813C329.3053358748298,57.3949838291264,248.02791733380457,8.279543830951368,175.87071277845988,42.242879143198664C103.41431057327972,76.34704239035025,93.79494320519305,170.9812938413882,81.28167332365135,250.07896920659033C70.17666984294237,320.27484674793965,64.84698225790005,396.69656628748305,111.28512138212992,450.4950937839243C156.20124167950087,502.5303643271138,231.32542653798444,500.4755392045468,300,503.46388370962813"></path>
                                    </svg>
                                    <i class='bx bxs-palette'></i>
                                </div>
                                <h4><a href="">Graphics Design</a></h4>
                                <p>For Graphics: Adobe Photoshop, Adobe illustrator, Abode XD, Figma, Canva. For Videos and Animation: Adobe After Effect, Adobe Premiere Pro.</p>
                            </div>
                        </div>

                        <div class="col-lg-6 d-flex align-items-stretch mt-4" data-aos="zoom-in" data-aos-delay="100">
                            <div class="icon-box iconbox-blue">
                                <div class="icon">
                                    <svg width="100" height="100" viewBox="0 0 600 600" xmlns="http://www.w3.org/2000/svg">
                                        <path stroke="none" stroke-width="0" fill="#f5f5f5" d="M300,521.0016835830174C376.1290562159157,517.8887921683347,466.0731472004068,529.7835943286574,510.70327084640275,468.03025145048787C554.3714126377745,407.6079735673963,508.03601936045806,328.9844924480964,491.2728898941984,256.3432110539036C474.5976632858925,184.082847569629,479.9380746630129,96.60480741107993,416.23090153303,58.64404602377083C348.86323505073057,18.502131276798302,261.93793281208167,40.57373210992963,193.5410806939664,78.93577620505333C130.42746243093433,114.334589627462,98.30271207620316,179.96522072025542,76.75703585869454,249.04625023123273C51.97151888228291,328.5150500222984,13.704378332031375,421.85034740162234,66.52175969318436,486.19268352777647C119.04800174914682,550.1803526380478,217.28368757567262,524.383925680826,300,521.0016835830174"></path>
                                    </svg>
                                    <i class='bx bxs-pen'></i>
                                </div>
                                <h4><a href="">Content Writing & Typing</a></h4>
                                <p>All Microsoft Office Apps.</p>
                            </div>
                        </div>



                    </div>
                </div><!-- End .content-->
            </div>

            <div class="content col-xl-5 d-flex flex-column justify-content-center">
                <img src="<?php echo $br['config']['theme_url']; ?>/imgs/g3.png" class="img-fluid" alt="">
            </div>

        </div>

    </div>
</section><!-- End Services Section -->

<!-- ======= Features Section ======= -->
<section id="projects" class="features">
    <div class="container">

        <h1 style="justify-content: center ; align-items: center; color: rgb(86, 82, 82); margin-left: 40%; margin-bottom: 3rem;">Recent Projects</h1>
        <div class="row">
            <div class="col-lg-3 col-md-4">
                <div class="icon-box">
                    <i class='bx bxs-graduation' style="color: #ffbb2c;"></i>
                    <h3><a href="">MiET BR App</a></h3>
                </div>
            </div>
            <div class="col-lg-3 col-md-4 mt-4 mt-md-0">
                <div class="icon-box">
                    <i class='bx bxs-videos' style="color: #5578ff;"></i>
                    <h3><a href="">Go Popular</a></h3>
                </div>
            </div>
            <div class="col-lg-3 col-md-4 mt-4 mt-md-0">
                <div class="icon-box">
                    <i class='bx bxs-phone-call' style="color: #e80368;"></i>
                    <h3><a href="">Letswetalk</a></h3>
                </div>
            </div>
            <br>
            <div class="col-lg-3 col-md-4 mt-4 mt-lg-0">
                <div class="icon-box">
                    <i class='bx bxs-note' style="color: #e361ff;"></i>
                    <h3><a href="">StudyKeyx</a></h3>
                </div>
            </div>
            <div class="col-lg-3 col-md-4 mt-4 ">
                <div class="icon-box">
                    <i class='bx bxl-youtube' style="color: #47aeff;"></i>
                    <h3><a href="">Letsbtube</a></h3>
                </div>
            </div>
            <div class="col-lg-3 col-md-4 mt-4">
                <div class="icon-box">
                    <i class='bx bxs-phone-call' style="color: #ffa76e;"></i>
                    <h3><a href="">World Talk</a></h3>
                </div>
            </div>

        </div>

    </div>
</section><!-- End Features Section -->


<!-- ======= Team Section ======= -->
<section id="team">
    <div class="container" data-aos="fade-up">
        <div class="section-header">
            <h3 style="font-size: 2.5rem;">Team</h3>
            <p style="font-size: 1.2rem;"> "Coming together is a beginning, staying together is progress, and working together is success."</p>
        </div>

        <div class="row">

            <div class="col-lg-3 col-md-6" data-aos="zoom-out" data-aos-delay="100">
                <div class="member">
                    <img src="<?php echo $br['config']['theme_url']; ?>/imgs/itsmebrijesh.jpeg" class="img-fluid" alt="">
                    <div class="member-info">
                        <div class="member-info-content">
                            <h4>Brijesh Chauhan</h4>
                            <span>Chief Executive Officer</span>
                            <div class="social">
                                <a href=""><i class="bi bi-twitter"></i></a>
                                <a href=""><i class="bi bi-facebook"></i></a>
                                <a href=""><i class="bi bi-instagram"></i></a>
                                <a href=""><i class="bi bi-linkedin"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6" data-aos="zoom-out" data-aos-delay="200">
                <div class="member">
                    <img src="<?php echo $br['config']['theme_url']; ?>/imgs/atul.jpeg" class="img-fluid" alt="">
                    <div class="member-info">
                        <div class="member-info-content">
                            <h4>Atul Pratap Singh</h4>
                            <span>CO-Chief Executive Officer</span>
                            <div class="social">
                                <a href=""><i class="bi bi-twitter"></i></a>
                                <a href=""><i class="bi bi-facebook"></i></a>
                                <a href=""><i class="bi bi-instagram"></i></a>
                                <a href=""><i class="bi bi-linkedin"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6" data-aos="zoom-out" data-aos-delay="300">
                <div class="member">
                    <img src="<?php echo $br['config']['theme_url']; ?>/imgs/prakhar.jpeg" class="img-fluid" alt="">
                    <div class="member-info">
                        <div class="member-info-content">
                            <h4>Prakhar Rastogi</h4>
                            <span>COO</span>
                            <div class="social">
                                <a href=""><i class="bi bi-twitter"></i></a>
                                <a href=""><i class="bi bi-facebook"></i></a>
                                <a href=""><i class="bi bi-instagram"></i></a>
                                <a href=""><i class="bi bi-linkedin"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6" data-aos="zoom-out" data-aos-delay="400">
                <div class="member">
                    <img src="<?php echo $br['config']['theme_url']; ?>/imgs/paridhi.jpeg" class="img-fluid" alt="">
                    <div class="member-info">
                        <div class="member-info-content">
                            <h4>Paridhi Jain</h4>
                            <span>CTO</span>
                            <div class="social">
                                <a href=""><i class="bi bi-twitter"></i></a>
                                <a href=""><i class="bi bi-facebook"></i></a>
                                <a href=""><i class="bi bi-instagram"></i></a>
                                <a href=""><i class="bi bi-linkedin"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
</section>

<!-- End Team Section -->



<!-- ======= Contact Section ======= -->
<section id="contact" class="contact section-bg">
    <div class="container">

        <div class="section-title">
            <h2>Contact</h2>
            <p>Whether it’s a compliment or an issue that needs resolving, we’re always ready to talk.</p>
        </div>

        <div class="row">

            <div class="col-lg-6">

                <div class="row">
                    <div class="col-md-12">
                        <div class="info-box">
                            <i class="bx bx-map"></i>
                            <h3>Our Address</h3>
                            <p>Cubical no.1, Miet Incubation Forum,
                                <br> Admin-Block, Miet, Nh-58,
                                <br> Meerut, UP, India <br> <br>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="info-box mt-4">
                            <i class="bx bx-envelope"></i>
                            <h3>Email Us</h3>
                            <p>info@brsoftsol.com</p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="info-box mt-4">
                            <i class="bx bx-phone-call"></i>
                            <h3>Call Us</h3>
                            <p>+91 7017442328</p>
                        </div>
                    </div>
                </div>

            </div>

            <div class="col-lg-6 mt-4 mt-lg-0">
                <form action="forms/contact.php" method="post" role="form" class="php-email-form">
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <input type="text" name="name" class="form-control" id="name" placeholder="First Name" required>
                        </div>
                        <div class="col-md-6 form-group mt-3 mt-md-0">
                            <input type="email" class="form-control" name="email" id="email" placeholder="Last Name" required>
                        </div>
                    </div>
                    <div class="form-group mt-3">
                        <input type="text" class="form-control" name="subject" id="subject" placeholder="Your Email" required>
                    </div>
                    <div class="form-group mt-3">
                        <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required>
                    </div>
                    <div class="form-group mt-3">
                        <textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea>
                    </div>
                    <div class="my-3">
                        <div class="loading">Loading</div>
                        <div class="error-message"></div>
                        <div class="sent-message">Your message has been sent. Thank you!</div>
                    </div>
                    <div class="text-center"><button type="submit">Send Message</button></div>
                </form>
            </div>

        </div>

    </div>
</section><!-- End Contact Section -->

</main><!-- End #main -->




<!-- ======= Testimonials Section ======= -->
<section id="testimonials" class="section-bg" style="background: #EEEEF5;">
    <div class="container" data-aso="zoom-in">

        <header class="section-header">
            <h3 style="font-size: 2.5rem;">Reviews</h3>
        </header>

        <div class="row justify-content-center" style="margin-top: -4rem;">
            <div class="col-lg-8">

                <div class="testimonials-slider swiper" data-aos="fade-up" data-aos-delay="100">
                    <div class="swiper-wrapper">


                        <div class="swiper-slide">
                            <div class="testimonial-item">
                                <img src="assets/img/test3.png" class="testimonial-img" alt="">
                                <h3>Vishwajeet Singh</h3>
                                <h4>Entrepreneur</h4>
                                <p>
                                    BR SOFTSOL is a dynamic and robust project management firm. It provides a better price. easier to use and great customer services!
                                </p>
                            </div>
                        </div><!-- End testimonial item -->

                        <div class="swiper-slide">
                            <div class="testimonial-item">
                                <img src="assets/img/test1.png" class="testimonial-img" alt="">
                                <h3>Simmi Singh</h3>
                                <h4>Store Owner</h4>
                                <p>
                                    Good quality and service unbeatable, Highly recommended!
                                </p>
                            </div>
                        </div><!-- End testimonial item -->

                        <div class="swiper-slide">
                            <div class="testimonial-item">
                                <img src="assets/img/test2.png" class="testimonial-img" alt="">
                                <h3>Naveen Chaudhary</h3>
                                <h4>Freelancer</h4>
                                <p>
                                    If you are looking for someone who manages multiple projects with various team members, BR SOFTSOL is the obvious choice !
                                </p>
                            </div>
                        </div><!-- End testimonial item -->


                    </div>
                    <div class="swiper-pagination"></div>
                </div>

            </div>
        </div>

    </div>
</section>

<!-- End Testimonials Section -->

<!-- footer -->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

<style>
    .hero {
    width: 100%;
    height: 100vh;
    background: url('<?php echo $br['config']['theme_url']; ?>/imgs/hero-bg.png') top center no-repeat;
    background-size: cover;
  }

  @media (min-width: 1024px) {
    .hero {
      background-attachment: fixed;
    }
  }
</style>
<!-- Vendor JS Files -->
<!-- <script src="assets/vendor/purecounter/purecounter.js"></script>
  <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script> -->
<script src="https://cdn.jsdelivr.net/gh/mcstudios/glightbox/dist/js/glightbox.min.js"></script>
<!-- <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script> -->
<script src="https://unpkg.com/swiper@8/swiper-bundle.min.js"></script>

<script>
    (function() {
        "use strict";

        /**
         * Easy selector helper function
         */
        const select = (el, all = false) => {
            el = el.trim()
            if (all) {
                return [...document.querySelectorAll(el)]
            } else {
                return document.querySelector(el)
            }
        }

        /**
         * Easy event listener function
         */
        const on = (type, el, listener, all = false) => {
            let selectEl = select(el, all)
            if (selectEl) {
                if (all) {
                    selectEl.forEach(e => e.addEventListener(type, listener))
                } else {
                    selectEl.addEventListener(type, listener)
                }
            }
        }

        /**
         * Easy on scroll event listener 
         */
        const onscroll = (el, listener) => {
            el.addEventListener('scroll', listener)
        }

        /**
         * Navbar links active state on scroll
         */
        let navbarlinks = select('#navbar .scrollto', true)
        const navbarlinksActive = () => {
            let position = window.scrollY + 200
            navbarlinks.forEach(navbarlink => {
                if (!navbarlink.hash) return
                let section = select(navbarlink.hash)
                if (!section) return
                if (position >= section.offsetTop && position <= (section.offsetTop + section.offsetHeight)) {
                    navbarlink.classList.add('active')
                } else {
                    navbarlink.classList.remove('active')
                }
            })
        }
        window.addEventListener('load', navbarlinksActive)
        onscroll(document, navbarlinksActive)

        /**
         * Scrolls to an element with header offset
         */
        const scrollto = (el) => {
            let header = select('#header')
            let offset = header.offsetHeight

            if (!header.classList.contains('header-scrolled')) {
                offset -= 16
            }

            let elementPos = select(el).offsetTop
            window.scrollTo({
                top: elementPos - offset,
                behavior: 'smooth'
            })
        }

        /**
         * Toggle .header-scrolled class to #header when page is scrolled
         */
        let selectHeader = select('#header')
        if (selectHeader) {
            const headerScrolled = () => {
                if (window.scrollY > 100) {
                    selectHeader.classList.add('header-scrolled')
                } else {
                    selectHeader.classList.remove('header-scrolled')
                }
            }
            window.addEventListener('load', headerScrolled)
            onscroll(document, headerScrolled)
        }

        /**
         * Back to top button
         */
        let backtotop = select('.back-to-top')
        if (backtotop) {
            const toggleBacktotop = () => {
                if (window.scrollY > 100) {
                    backtotop.classList.add('active')
                } else {
                    backtotop.classList.remove('active')
                }
            }
            window.addEventListener('load', toggleBacktotop)
            onscroll(document, toggleBacktotop)
        }

        /**
         * Mobile nav toggle
         */
        on('click', '.mobile-nav-toggle', function(e) {
            select('#navbar').classList.toggle('navbar-mobile')
            this.classList.toggle('bi-list')
            this.classList.toggle('bi-x')
        })

        /**
         * Mobile nav dropdowns activate
         */
        on('click', '.navbar .dropdown > a', function(e) {
            if (select('#navbar').classList.contains('navbar-mobile')) {
                e.preventDefault()
                this.nextElementSibling.classList.toggle('dropdown-active')
            }
        }, true)

        /**
         * Scrool with ofset on links with a class name .scrollto
         */
        on('click', '.scrollto', function(e) {
            if (select(this.hash)) {
                e.preventDefault()

                let navbar = select('#navbar')
                if (navbar.classList.contains('navbar-mobile')) {
                    navbar.classList.remove('navbar-mobile')
                    let navbarToggle = select('.mobile-nav-toggle')
                    navbarToggle.classList.toggle('bi-list')
                    navbarToggle.classList.toggle('bi-x')
                }
                scrollto(this.hash)
            }
        }, true)

        /**
         * Scroll with ofset on page load with hash links in the url
         */
        window.addEventListener('load', () => {
            if (window.location.hash) {
                if (select(window.location.hash)) {
                    scrollto(window.location.hash)
                }
            }
        });

        /**
         * Porfolio isotope and filter
         */
        window.addEventListener('load', () => {
            let portfolioContainer = select('.portfolio-container');
            if (portfolioContainer) {
                let portfolioIsotope = new Isotope(portfolioContainer, {
                    itemSelector: '.portfolio-item'
                });

                let portfolioFilters = select('#portfolio-flters li', true);

                on('click', '#portfolio-flters li', function(e) {
                    e.preventDefault();
                    portfolioFilters.forEach(function(el) {
                        el.classList.remove('filter-active');
                    });
                    this.classList.add('filter-active');

                    portfolioIsotope.arrange({
                        filter: this.getAttribute('data-filter')
                    });

                }, true);
            }

        });

        /**
         * Initiate portfolio lightbox 
         */
        const portfolioLightbox = GLightbox({
            selector: '.portfolio-lightbox'
        });

        /**
         * Portfolio details slider
         */
        new Swiper('.portfolio-details-slider', {
            speed: 400,
            loop: true,
            autoplay: {
                delay: 5000,
                disableOnInteraction: false
            },
            pagination: {
                el: '.swiper-pagination',
                type: 'bullets',
                clickable: true
            }
        });

    })()

    new Swiper('.testimonials-slider', {
        speed: 600,
        loop: true,
        autoplay: {
            delay: 5000,
            disableOnInteraction: false
        },
        slidesPerView: 'auto',
        pagination: {
            el: '.swiper-pagination',
            type: 'bullets',
            clickable: true
        }
    });
</script>