<?php
$thms = $br['config']['theme_url'];
$bg = $br['config']['theme_url'] . '/imgs/welcome1.png';
?>

<style>
    .main-login-box{
        background-color: #F9F7F7;
        width: 20rem;
        margin-left: 15rem;
        margin-top:5%;
        margin-bottom:150px;
        border-radius: 20px;
    }
    .login-title{
        font-size: 2rem;
        margin-top: 2rem;
    }
    .login-top-text{
        line-height: 5px;
    }
    .rounded-circle{

        width: 100px;
        height: 100px;
        margin-top: -30px;

    }
    .alert-danger{
        margin-top: -40px;
        background: #F9F7F7;
        border: 1px solid #ffffff;
 
    }
    .input-field{
      margin-top: -12px;
      
    }
    .sub-btn{
        margin-top: -50px;
    }
    .text-black-50 a{
		text-decoration: none;
	}


    @media only screen and (max-width: 600px){
        .main-login-box{
            margin-left: 2rem;
            margin-top: 17%;
        }
    }


</style>
<section id="login-form">
    <div class="row m-0">
        <div class="col-lg-4 offset-lg-2 main-login-box" >
            <div class="text-center pb-5 login-top-text">
                <h1 class="login-title text-dark">Login</h1>
                <p class="p-1 m-0 font-ubuntu text-black-50">Login and enjoy additional features</p>

                <span class="font-ubuntu text-black-50">Create a new <a href="<?php echo $br['config']['site_url'].'/index.php?link1=register'; ?>">account</a></span>

            </div>
            <div class="upload-profile-image d-flex justify-content-center pb-5">
                <div class="text-center ">
                    <img src="<?php echo $thms; ?>/imgs/beard.png"  class="img rounded-circle" alt="profile">
                </div>
            </div>
            <div class="d-flex justify-content-center">
                <form method="post" enctype="multipart/form-data" id="log-form">
                <div class="alert alert-danger errors" role="alert" style="display: none;"></div>
                <div class="alert alert-success success" role="alert" style="display: none;"></div>
                    <div class="form-row my-4">
                        <div class="col input-field">
                            <input type="email" required name="email" id="email" class="form-control" placeholder="Email*">
                        </div>
                    </div>

                    <div class="form-row my-4">
                        <div class="col input-field">
                            <input type="password" required name="password" id="password" class="form-control" placeholder="Password*">
                        </div>
                    </div>

                    <div class="submit-btn text-center my-5">
                        <button type="submit" class="btn btn-warning rounded-pill text-dark px-5 sub-btn" >Login</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</section>

<script>
    var working = false;
    var $this = $('#log-form');
    var $statee = $this.find('.errors');
    var $states = $this.find('.success');
    $('#login-form').css("background", "url('<?php echo $bg; ?>') no-repeat");
    $('#login-form').css("background-size", "cover");


    $(function() {
        $this.ajaxForm({
            url: Br_Ajax_Requests_File() + '?f=login',
            beforeSend: function() {
                    working = true;
                    // $this.find('button').attr("disabled", true);
                    // $this.find('.add_wow_loader').addClass('btn-loading');
                
            },
            success: function(data) {
                if (data.status == 200) {
                    $states.show();
                    $states.addClass('success');
                    $states.html('<?php echo '<b>welcome</b>' ?>');
                    $this.find('.add_wow_loader').removeClass('btn-loading');
                    setTimeout(function() {
                        window.location.href = data.location;
                    }, 1000);
                } else if (data.status == 300) {
                    $statee.show();
                    $statee.html('<?php echo 'redirecting' ?>');
                    window.location.href = data.location;
                } else {
                    $statee.show();
                    $this.find('button').attr("disabled", false);
                    $this.find('.add_wow_loader').removeClass('btn-loading');
                    $statee.html(data.errors);
                }
                working = false;
            }
        });
    });
</script>