<div id="welcomeheader" class="navbar-default">
	<div class="container">
		<div class="logo">
			<a href="<?php echo $br['config']['site_url'];?>"><img src="<?php echo $br['config']['theme_url'];?>/img/logo.<?php echo $br['config']['logo_extension'];?>" alt="Logo"> </a>
		</div>
		<?php if ($br['config']['user_registration'] == 1): ?>
			<ul class="nav navbar-nav navbar-right">
				<li class="absul-right">
					<a class="mdbtn" href="<?php echo Br_SeoLink('index.php?link1=register');?>"><?php echo "Register"; ?></a>
				</li>
			</ul>
		<?php endif ?>
	</div>
</div>