<div id="welcomeheader" class="navbar-default">
	<div class="container">
		<div class="logo">
			<a href="<?php echo $br['config']['site_url'];?>"><img src="<?php echo $br['config']['theme_url'];?>/img/logo.png" alt="Logo"> </a>
		</div>
		
			<ul class="nav navbar-nav navbar-right">
				<li class="absul-right">
					<a class="mdbtn" href="<?php echo $br['config']['site_url'];?>">login</a>
				</li>
			</ul>
		
	</div>
</div>