<section id="welcome">
    <div>
        <img src="<?php echo $br['user']['profile_pic']; ?>" alt="Your Picture Here" class="pic">
        <h1 class="welcomTxt">Welcome, <?php echo $br['user']['fname'] . " " . $br['user']['lname'] ?></h1>
        <?php if ($br['config']['afternoon_system'] == 1) { ?>
			<div class="alert alert-dismissible greetalert hidden" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close" onclick="setCookie('day_status', '1', 3);"><span aria-hidden="true">&times;</span></button>
				<div id="daynightmsg"></div>
			</div>
			<?php } ?>
            <?php 
            if (Br_IsThereAnnouncement() === true) { 
				$announcement = Br_GetHomeAnnouncements();
			?>
			<div class="home-announcement">
				<div class="alert alert-success" style="background-color: white;">
					<span class="close announcements-option" data-toggle="tooltip" onclick="Br_ViewAnnouncement(<?php echo $announcement['id']; ?>);" title="<?php echo 'hide'; ?>">
						<i class="fa fa-remove"></i>
					</span>
					<?php echo $announcement['text']; ?>
				</div>
			</div>
			<!-- .home-announcement -->
			<?php } ?>
    </div>
</section>

<!--//////////////////////// Newsfeed ////////////////////////-->

<section id="Newsfeed">
    <h1 class="headTxt">
        <hr> NewsFeed
        <hr>
    </h1>
    <div class="news">
        <div class="row">


            <div class="col-md-5 mb-4">
                <div class="bg-image hover-overlay ripple shadow-2-strong rounded-5" data-mdb-ripple-color="light">
                    <img src="<?php echo $br['config']['theme_url'] . '/imgs/bg1.png' ?>" class="img-fluid" />
                    <a href="#!">
                        <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                    </a>
                </div>
            </div>

            <div class="col-md-7 mb-4">
                <span class="badge bg-danger px-2 py-1 shadow-1-strong mb-3">News of the day</span>
                <h4><strong> 
                    Improve security and privacy by updating http cache
                </strong></h4>
                <p class="text-muted">
                Leaky resources from spectre vulnerabilities.
                     The 'Spectre vulnerabilitiy.' allows apage to read an OS Process's memory.
                     This means an attacker can gain unauthorized acess to cross-origin data.
                     As a consequence, modern web browsers have restricted usage of some of their features 
                     such as SharedArrayBuffer or hifh resolution timer- to page with cross-origin isolation.

                </p>

                <button type="button" class="btn btn-primary">Read more</button>
            </div>
        </div>
    </div>

    <div class="news">
        <div class="row gx-5">

            <div class="col-md-5 mb-4 ">
                <div class="bg-image hover-overlay ripple shadow-2-strong rounded-5" data-mdb-ripple-color="light">
                    <img src="https://c4.wallpaperflare.com/wallpaper/431/451/684/the-most-beautiful-picture-of-nature-wallpaper-preview.jpg" class="img-fluid" />
                    <a href="#!">
                        <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                    </a>
                </div>
            </div>

            <div class="col-md-7 mb- 4">
                <!-- <span class="badge bg-danger px-2 py-1 shadow-1-strong mb-3">News of the day</span> -->
                <h4><strong> WebAssembly feature detection </strong></h4>
                <p class="text-muted">
                 
               WebAssembly 1.0 was released four years ago,but development didn't stop there.
                    New features are added through the 'Proposal standarization process.' As is generally 
                    the case with new features on the web, their implementation order and timelines can 
                    differ significantly between different engines. 
                    Some new features improve coe size by adding new instructions for common operations, some
                    add powerful performance primitives, and other improve developer experience and integartion
                    with the rest of the web.
                </p>
                <button type="button" class="btn btn-primary">Read more</button>
            </div>
        </div>
    </div>

    <!--Section: News of the day-->
</section>

<!-- //////////////////////// Projects /////////////////////////// -->
<section id="project">
    <div class="container-fluid">
        <h1 class="headTxt">
            <hr>
            Projects
            <hr>
        </h1>
        <div class="row justify-content-evenly">
            <div class="card col-md-3">
                <img src="<?php echo $br['config']['theme_url'].'/imgs/mietbrapp.jpg'?>" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">MiET BR App</h5>
                    <p class="card-text"> MiET BR App is a simple and awesome Educational life management app.
                        It gives you a quick and simple experience. It provides proper guidance about competitive exam and internships.
                        It provides all the bsic needs like Timetable, Notes, Assignments etc. It also helps students to
                        ask doubts from faculties,peers and increase peace of learning.
                    </p>
                    <a href="#" class="btn btn-primary">Know More</a>
                </div>
            </div>
            
            <div class="card col-md-3">
                <img src="<?php echo $br['config']['theme_url'].'/imgs/i.png'?>" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Go Popular </h5>
                    <p class="card-text"> Go Popular is a short video community app craeted locally.This is a platform
                        to forecast talents to the whole world. This funny video community maker app lets you follow
                        your favourite entertainer for good fun and entertainment. The app is used by young people
                        as an outlet to express themselves.
                    </p>
                    <a href="#" class="btn btn-primary">Know More</a>
                </div>
            </div>
            <div class="card col-md-3">
                <img src="<?php echo $br['config']['theme_url'].'/imgs/letwetalk.jpg'?>" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Letswetalk</h5>
                    <p class="card-text">Letswetalk is a website basically used for group video chat, voice calls and 
                        text-messaging. Be together whenever, with our freeall-in-one communication website, completed with 
                        text-messaging , calling and video chats. Easily sync your messages and contacts to your
                        Android phone and connect wuth anyone,anywhere.</p>
                    <a href="#" class="btn btn-primary">Know More</a>
                </div>
            </div>
            <div class="card col-md-3">
                <img src="<?php echo $br['config']['theme_url'].'/imgs/splash_logo.png'?>" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">StudyKeyx</h5>
                    <p class="card-text"> Connect with Studykeyx is an efficient and transparent manner right from 
                        undertanding the topics to clearing the exam. We offer you a on-step solution for all your 
                        learning needs. With aq simple user interface, design, and exciting features, our app is the
                    go-to solution for the students.                 </p>
                    <a href="#" class="btn btn-primary">Know More</a>
                </div>
            </div>
            <div class="card col-md-3">
                <img src="<?php echo $br['config']['theme_url'].'/imgs/letsbtube.jpg'?>" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Letsbtube</h5>
                    <p class="card-text">Letsbtube is a most popular distribution website or platform on the 
                        internet. It was originally created as a platform for anyone to post any video content 
                    they desired. It was hoped that usewrs could use the site to upload, share, and view content 
                    without any restriction. </p>
                    <a href="#" class="btn btn-primary">Know More</a>
                </div>
            </div>
            <div class="card col-md-3">
                <img src="<?php echo $br['config']['theme_url'].'/imgs/worldtalk.jpg'?>" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">World Talk </h5>
                    <p class="card-text"> World Talk is a social networking website. It is a type of social network 
                        where people stay in touch with friends oe family members through online profiles and 
                       updates, or find new friends through similar intrests.  People engaged in social networking
                       may be doing so as a personal or a buisness ebdeavor.  </p>
                    <a href="#" class="btn btn-primary">Know More</a>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- //////////////////////// Team Members //////////////////////// -->
<section id="team">
    <div class='container'>
        <div class="header">
            <div class="teamTitle">Meet Our New Members</div>

        </div>
        <div class="row">
            <div class="card col-lg-3 mt-100">
                <div class="card-content">
                    <div class="card-body p-0">
                        <div class="profile"> <img src="<?php echo $br['config']['theme_url'] . '/imgs/itsmebrijesh.jpeg' ?>"> </div>
                        <div class="card-title"> Brijesh Chauhan<br /> <small>(CEO & Founder)</small>
                        </div>
                        <div class="card-subtitle">
                            <p> <small class="text-muted"> Email: brijeshchauhan19@gmail.com <br>
                                     phone: +91 7017442328<br>
                                     Address: Vill.Dulhera Chauhan, Modipuram , Meerut
                                </small> </p>
                            <ul class="social">
                                <li class="email"><a href="mailto:brsoftsol@gmail.com"><img src="email.png" alt=""></a></li>
                                <li class="phone"></i><a href="tel:+91 00000000"><img src="phone.png" alt=""></a>
                                </li>
                                <li class="linkedin"><a href="https://www.linkedin.com/company/brsoftsol/"><img src="linkedin.jpg" alt=""></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card col-lg-3 mt-100">
                <div class="card-content">
                    <div class="card-body p-0">
                        <div class="profile"> <img src="https://picsum.photos/500/300?random=1"> </div>
                        <div class="card-title"> AtulPratap Singh<br /> <small> (CO-CEO)</small> </div>
                        <div class="card-subtitle">
                            <p> <small class="text-muted"> Email:  Pratapsinghatul111@gmail.com
                                  Phone: +91 8192002404
                                  Address: O-149 PallavPuram, Phase-2, Meerut
                                </small> </p>
                                <ul class="social">
                                <li class="email"><a href="mailto:brsoftsol@gmail.com"><img src="email.png" alt=""></a></li>
                                <li class="phone"></i><a href="tel:+91 00000000"><img src="phone.png" alt=""></a>
                                </li>
                                <li class="linkedin"><a href="https://www.linkedin.com/company/brsoftsol/"><img src="linkedin.jpg" alt=""></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card col-lg-3 mt-100">
                <div class="card-content">
                    <div class="card-body p-0">
                        <div class="profile"> <img src="https://picsum.photos/500/300?random=2"> </div>
                        <div class="card-title"> Prakhar Rastogi <br /> <small>(COO)</small> </div>
                        <div class="card-subtitle">
                            <p> <small class="text-muted">  Email: Prakharrastogi99@gmail.com<br>
                                Phone: +91 9690843212<br>
                                Address: S-13 Modipuram, Meerut
                                </small> </p>
                            <ul class="social">
                                <li class="email"><a href="mailto:brsoftsol@gmail.com"><img src="email.png" alt=""></a></li>
                                <li class="phone"></i><a href="tel:+91 00000000"><img src="phone.png" alt=""></a>
                                </li>
                                <li class="linkedin"><a href="https://www.linkedin.com/company/brsoftsol/"><img src="linkedin.jpg" alt=""></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section>
<!-- .........................roadmap................... -->
<section id="roadmap">
    <h1 class="headTxt">
        <hr>
        Roadmap
        <hr>
    </h1>
    <div class="page">

        <div class="timeline">
            <div class="timeline__group">
                <span class="timeline__year time" aria-hidden="true">2021</span>
                <div class="timeline__cards">
                    <div class="timeline__card card1">
                        <header class="card__header">
                            <time class="time" datetime="2008-02-02">
                                <span class="time__day">4</span>
                                <span class="time__month">sept</span>
                            </time>
                        </header>
                        <div class="card__content">
                            <p> "Br SoftSol is an IT Services providing company". And at the very starting it's only a 
                                BR team which work together with positive hope.
                            </p>
                        </div>
                    </div>
                    <div class="timeline__card card1">
                        <header class="card__header">
                            <time class="time" datetime="2008-09-01">
                                <span class="time__day"> 10 </span>
                                <span class="time__month">Dec</span>
                            </time>
                            <h3 class="card__title r-title">Br Team as a Br SoftSol
                        </header>
                        <div class="card__content">
                            <p> </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="timeline__group">
                <span class="timeline__year time" aria-hidden="true">2022</span>
                <div class="timeline__cards">
                    <div class="timeline__card card1">
                        <header class="card__header">
                            <time class="time" datetime="2008-07-14">
                                <span class="time__day">27</span>
                                <span class="time__month">Apr</span>
                            </time>
                        </header>
                        <div class="card__content">
                            <p>Br SOftSol held a well-defined Orientation to provide a proper knoeledge about Our company.
                                In this Orientation we discuss about the features, services , benefits to join us and the infrastructure 
                                provided by the Br softsol to the members.
                                 </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="timeline__group">
               
                <div class="timeline__cards">
                    <div class="timeline__card card1">
                        <header class="card__header">
                            <time class="time" datetime="2008-08-18">
                                <span class="time__day">5</span>
                                <span class="time__month">May</span>
                            </time>
                        </header>
                        <div class="card__content">
                            <p> On 5th of may we are going to Organize an event basically an interview session in which
                                we choose our new members for company.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>



<script type="text/javascript">
    function Br_ViewAnnouncement(id) {
        var announcement_container = $('.home-announcement');
        $.get(Br_Ajax_Requests_File() + '?f=update_announcement_views', {
            id: id
        }, function(data) {
            if (data.status == 200) {
                announcement_container.slideUp(200, function() {
                    $(this).remove();
                });
            }
        });
    }

    function setCookie(cname, cvalue, exdays) {
        var d = new Date();
        d.setTime(d.getTime() + (exdays * 60 * 60 * 1000));
        var expires = "expires=" + d;
        document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
    }

    function getCookieValue(a) {
        var b = document.cookie.match('(^|;)\\s*' + a + '\\s*=\\s*([^;]+)');
        return b ? b.pop() : '';
    }

    $(function() {
        var is_day_enabled = getCookieValue('day_status');
        var myDate = new Date();
        var hrs = myDate.getHours();
        var greet;
        var color;
        var quote;
        if (hrs < 12) {
            greet = '<?php echo 'Good Morning'; ?>, <?php echo $br['user']['name'] ?> <img src="<?php echo $br['config']['theme_url']; ?>/imgs/park.png"/>';
            color = '#7FC583';
            quote = '<?php echo $br['config']['goodMorningQuote']; ?>';
        } else if (hrs >= 12 && hrs <= 18) {
            greet = '<?php echo 'Good Afternoon'; ?>, <?php echo $br['user']['name'] ?> <img src="<?php echo $br['config']['theme_url']; ?>/imgs/desert.png"/>';
            color = '#ffc107';
            quote = '<?php echo $br["config"]["goodAfternoonQuote"]; ?>';
        } else if (hrs >= 18 && hrs <= 24) {
            greet = '<?php echo 'Good Evening'; ?>, <?php echo $br['user']['name'] ?> <img src="<?php echo $br['config']['theme_url']; ?>/imgs/sea.png"/>';
            color = '#FF4F70';
            quote = '<?php echo $br["config"]["goodEveningQuote"]; ?>';
        }
        if (is_day_enabled != 1) {
            setTimeout(function() {
                $('.greetalert').css('border-left', '2.5px solid ' + color);
                $('#daynightmsg').html('<div class="small-texts">' + greet + '</div><p>' + quote + '</p>');
                $('.greetalert').removeClass('hidden');
            }, 100);
        }
    });
</script>