<div class="flex-container">
    <!--comment-->
    <div class="flex-item-left">
        <h1 class="heading">About us</h1>
        <p class="paras">BR Softsol is an IT consulting and solution providing organization for next generation business
            collaborates throughout the world. With comprehensive intelligence system across diverse industries and
            domains, we dedicatedly work over the client's project to turn them into some most successful and
            high-performance organizations. We provide our customers with high-quality, cutting-edge business
            solutions. </p>
        <button class="btn1"><a href="#a" style="font-size:18px;">Explore more</a></button>

    </div>
    <div class="flex-item-right">
        <img class="ill" src="<?php echo $br['config']['theme_url'] . '/imgs/web.svg' ?>">
    </div>
</div>

<style>
    .flex-item-left {
        background-image: url("<?php echo $br['config']['theme_url'] . '/imgs/Untitled-3.svg' ?>");
        background-size: cover;
    }

    .flex-item-right {
        background-image: url("<?php echo $br['config']['theme_url'] . '/imgs/circle3.png' ?>");
        background-repeat: no-repeat;
    }

    .flex-item-left1 {
        background-image: url("<?php echo $br['config']['theme_url'] . '/imgs/circle1.png' ?>");
        background-repeat: no-repeat;
    }
</style>

<div id="a"></div>
<div class="flex-container1">
    <div class="flex-item-left1">
        <img class="world" src="<?php echo $br['config']['theme_url'] . '/imgs/world.svg' ?>">
    </div>
    <div class="flex-item-right1">


        <img class="about" style="width:200px; height:80px ;justify-content: center;align-items:center; margin:auto; display:flex;" src="<?php echo $br['config']['theme_url'] . '/imgs/new.png' ?>">
        <p class="paras">BR Softsol is a global IT consultancy and solution provider for next-generation corporate collaboration.

            Sharpening edges via innovation and continual learning, all of these aspects contribute to success. Our
            objective is to strive toward realizing our vision for the future.Our solutions are undeniably pricey,
            which implies we
            appreciate your money and demonstrate that we are aiming to please you and keep you with us by
            developing great connections rather than focusing just on short-term profits. We follow business ethics
            and ideals, and we do not cross business lines. We do assignments on time and with high quality. Our
            work is the greatest in the business, and we provide you with more than you expected. We are convinced
            that providing what you require will lead to you returning to us for any future business ventures.
            We have shaped our organisation in such a way that it is agile in rising importance of highly
            integrated, software and services.
        </p>
    </div>
</div>


<section id="team" class="team-area pt-120">
    <div class="container ">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="section-title text-center pb-30">
                    <div class="line m-auto"></div>
                    <img class="about" style="width:200px; height:80px ;justify-content: center;align-items:center; margin:auto; display:flex; margin-bottom:30px;" src="<?php echo $br['config']['theme_url'] . '/imgs/new1.png' ?>">
                </div> <!-- section title -->
            </div>
        </div> <!-- row -->
        <div class="row  justify-content-center">
            <div class=" col-lg-3 col-md-7 col-sm-8">
                <div class="single-team text-center mt-30 wow fadeIn" data-wow-duration="1s" data-wow-delay="0.2s">
                    <div class="team-image">
                        <img src="<?php echo $br['config']['theme_url'] . '/imgs/atul.jpeg' ?>" alt="Team">
                        <div class="social">
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="team-content">
                        <h5 class="holder-name"><a href="#">Atul Pratap Singh</a></h5>
                        <p class="text">(CO-CEO)</p>
                    </div>
                </div> <!-- single team -->
            </div>
            <div class="col-lg-3 col-md-7 col-sm-8">
                <div class="single-team text-center mt-30 wow fadeIn" data-wow-duration="1s" data-wow-delay="0.5s">
                    <div class="team-image">
                        <img src="<?php echo $br['config']['theme_url'] . '/imgs/itsmebrijesh.jpeg' ?>" alt="Team">
                        <div class="social">
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="team-content">
                        <h5 class="holder-name"><a href="#">Brijesh Chauhan</a></h5>
                        <p class="text">(CEO & Founder)</p>
                    </div>
                </div> <!-- single team -->
            </div>
            <div class="col-lg-3 col-md-7 col-sm-8">
                <div class="single-team text-center mt-30 wow fadeIn" data-wow-duration="1s" data-wow-delay="0.8s">
                    <div class="team-image">
                        <img src="<?php echo $br['config']['theme_url'] . '/imgs/prakhar.jpeg' ?>" alt="Team">
                        <div class="social">
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="team-content">
                        <h5 class="holder-name"><a href="#">Prakhar Rastogi</a></h5>
                        <p class="text">(COO)</p>
                    </div>
                </div> <!-- single team -->
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-3 col-md-7 col-sm-8">
                <div class="single-team text-center mt-30 wow fadeIn" data-wow-duration="1s" data-wow-delay="0.8s">
                    <div class="team-image">
                        <img src="<?php echo $br['config']['theme_url'] . '/imgs/paridhi.jpeg' ?>" alt="Team">
                        <div class="social">
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="team-content">
                        <h5 class="holder-name"><a href="#">Paridhi Jain</a></h5>
                        <p class="text">(CTO)</p>
                    </div>
                </div> <!-- single team -->
            </div>
            <div class="col-lg-3 col-md-7 col-sm-8">
                <div class="single-team text-center mt-30 wow fadeIn" data-wow-duration="1s" data-wow-delay="0.8s">
                    <div class="team-image">
                        <img src="<?php echo $br['config']['theme_url'] . '/imgs/choti.jpeg' ?>" alt="Team">
                        <div class="social">
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="team-content">
                        <h5 class="holder-name"><a href="#">Shreshtha Johri</a></h5>
                        <p class="text">(PRESIDENT)</p>
                    </div>
                </div> <!-- single team -->
            </div>
            <div class="col-lg-3 col-md-7 col-sm-8">
                <div class="single-team text-center mt-30 wow fadeIn" data-wow-duration="1s" data-wow-delay="0.8s">
                    <div class="team-image">
                        <img src="<?php echo $br['config']['theme_url'] . '/imgs/kansal.jpeg' ?>" alt="Team">
                        <div class="social">
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="team-content">
                        <h5 class="holder-name"><a href="#">Shruti Kansal</a></h5>
                        <p class="text">(VICE-PRESIDENT)</p>
                    </div>
                </div> <!-- single team -->
            </div>
        </div> <!-- row -->
    </div> <!-- container -->
</section>